// 敬語変換辞書
// 動詞の原形 → [尊敬語, 謙譲語, 丁寧語]

export interface KeigoEntry {
  sonkeigo: string;   // 尊敬語（相手の動作に使う）
  kenjogo: string;    // 謙譲語（自分の動作に使う）
  teineigo: string;   // 丁寧語（ます・です形）
}

// Pattern: [plain verb/phrase, { sonkeigo, kenjogo, teineigo }]
export const keigoDict: [string, KeigoEntry][] = [
  // --- 基本動詞 ---
  ["いる", { sonkeigo: "いらっしゃる", kenjogo: "おる", teineigo: "います" }],
  ["ある", { sonkeigo: "ございます", kenjogo: "ございます", teineigo: "あります" }],
  ["行く", { sonkeigo: "いらっしゃる", kenjogo: "参る", teineigo: "行きます" }],
  ["来る", { sonkeigo: "いらっしゃる", kenjogo: "参る", teineigo: "来ます" }],
  ["する", { sonkeigo: "なさる", kenjogo: "いたす", teineigo: "します" }],
  ["言う", { sonkeigo: "おっしゃる", kenjogo: "申す", teineigo: "言います" }],
  ["食べる", { sonkeigo: "召し上がる", kenjogo: "いただく", teineigo: "食べます" }],
  ["飲む", { sonkeigo: "召し上がる", kenjogo: "いただく", teineigo: "飲みます" }],
  ["見る", { sonkeigo: "ご覧になる", kenjogo: "拝見する", teineigo: "見ます" }],
  ["知る", { sonkeigo: "ご存知である", kenjogo: "存じる", teineigo: "知っています" }],
  ["もらう", { sonkeigo: "お受け取りになる", kenjogo: "いただく", teineigo: "もらいます" }],
  ["あげる", { sonkeigo: "差し上げる", kenjogo: "差し上げる", teineigo: "あげます" }],
  ["くれる", { sonkeigo: "くださる", kenjogo: "くださる", teineigo: "くれます" }],
  ["もって行く", { sonkeigo: "お持ちになる", kenjogo: "お持ちする", teineigo: "持って行きます" }],
  ["思う", { sonkeigo: "お思いになる", kenjogo: "存じる", teineigo: "思います" }],
  ["会う", { sonkeigo: "お会いになる", kenjogo: "お目にかかる", teineigo: "会います" }],
  ["聞く", { sonkeigo: "お聞きになる", kenjogo: "伺う", teineigo: "聞きます" }],
  ["聞かせる", { sonkeigo: "お聞かせになる", kenjogo: "申し上げる", teineigo: "聞かせます" }],
  ["話す", { sonkeigo: "お話しになる", kenjogo: "申し上げる", teineigo: "話します" }],
  ["読む", { sonkeigo: "お読みになる", kenjogo: "拝読する", teineigo: "読みます" }],
  ["書く", { sonkeigo: "お書きになる", kenjogo: "書かせていただく", teineigo: "書きます" }],
  ["使う", { sonkeigo: "お使いになる", kenjogo: "使わせていただく", teineigo: "使います" }],
  ["待つ", { sonkeigo: "お待ちになる", kenjogo: "お待ちする", teineigo: "待ちます" }],
  ["訪ねる", { sonkeigo: "おいでになる", kenjogo: "伺う", teineigo: "訪ねます" }],
  ["訪問する", { sonkeigo: "おいでになる", kenjogo: "伺う", teineigo: "訪問します" }],
  ["もらえる", { sonkeigo: "いただける", kenjogo: "いただける", teineigo: "もらえます" }],
  ["受け取る", { sonkeigo: "お受け取りになる", kenjogo: "受領する", teineigo: "受け取ります" }],
  ["送る", { sonkeigo: "お送りになる", kenjogo: "お送りする", teineigo: "送ります" }],
  ["渡す", { sonkeigo: "お渡しになる", kenjogo: "お渡しする", teineigo: "渡します" }],
  ["連絡する", { sonkeigo: "ご連絡なさる", kenjogo: "ご連絡申し上げる", teineigo: "連絡します" }],
  ["確認する", { sonkeigo: "ご確認なさる", kenjogo: "確認いたす", teineigo: "確認します" }],
  ["説明する", { sonkeigo: "ご説明なさる", kenjogo: "ご説明申し上げる", teineigo: "説明します" }],
  ["相談する", { sonkeigo: "ご相談なさる", kenjogo: "ご相談申し上げる", teineigo: "相談します" }],
  ["報告する", { sonkeigo: "ご報告なさる", kenjogo: "ご報告申し上げる", teineigo: "報告します" }],
  ["依頼する", { sonkeigo: "ご依頼なさる", kenjogo: "お願いする", teineigo: "依頼します" }],
  ["お願いする", { sonkeigo: "お願いなさる", kenjogo: "お願い申し上げる", teineigo: "お願いします" }],
  ["承知する", { sonkeigo: "ご承知なさる", kenjogo: "承知いたす", teineigo: "承知します" }],
  ["了解する", { sonkeigo: "ご了承なさる", kenjogo: "了解いたす", teineigo: "了解します" }],
  ["参加する", { sonkeigo: "ご参加なさる", kenjogo: "参加いたす", teineigo: "参加します" }],
  ["利用する", { sonkeigo: "ご利用なさる", kenjogo: "利用いたす", teineigo: "利用します" }],
  ["購入する", { sonkeigo: "お買い求めになる", kenjogo: "購入いたす", teineigo: "購入します" }],
  ["帰る", { sonkeigo: "お帰りになる", kenjogo: "失礼する", teineigo: "帰ります" }],
  ["寝る", { sonkeigo: "お休みになる", kenjogo: "休ませていただく", teineigo: "寝ます" }],
  ["起きる", { sonkeigo: "お起きになる", kenjogo: "起きさせていただく", teineigo: "起きます" }],
  ["着る", { sonkeigo: "お召しになる", kenjogo: "着させていただく", teineigo: "着ます" }],
  ["もつ", { sonkeigo: "お持ちになる", kenjogo: "お持ちする", teineigo: "持ちます" }],
  ["見せる", { sonkeigo: "お見せになる", kenjogo: "ご覧に入れる", teineigo: "見せます" }],
  ["教える", { sonkeigo: "お教えになる", kenjogo: "ご説明申し上げる", teineigo: "教えます" }],
  ["手伝う", { sonkeigo: "お手伝いくださる", kenjogo: "お手伝いする", teineigo: "手伝います" }],
  ["借りる", { sonkeigo: "お借りになる", kenjogo: "拝借する", teineigo: "借ります" }],
  ["貸す", { sonkeigo: "お貸しくださる", kenjogo: "お貸しする", teineigo: "貸します" }],
  ["案内する", { sonkeigo: "ご案内なさる", kenjogo: "ご案内する", teineigo: "案内します" }],
  ["準備する", { sonkeigo: "ご準備なさる", kenjogo: "準備いたす", teineigo: "準備します" }],
  ["検討する", { sonkeigo: "ご検討なさる", kenjogo: "検討いたす", teineigo: "検討します" }],
  ["判断する", { sonkeigo: "ご判断なさる", kenjogo: "判断いたす", teineigo: "判断します" }],
];

// 動詞の活用形マッピング（原形 → 様々な活用形）
export const verbConjugations: Record<string, string> = {
  "行きます": "行く",
  "行った": "行く",
  "行って": "行く",
  "来ます": "来る",
  "来た": "来る",
  "来て": "来る",
  "します": "する",
  "した": "する",
  "して": "する",
  "言います": "言う",
  "言った": "言う",
  "言って": "言う",
  "食べます": "食べる",
  "食べた": "食べる",
  "食べて": "食べる",
  "飲みます": "飲む",
  "飲んだ": "飲む",
  "飲んで": "飲む",
  "見ます": "見る",
  "見た": "見る",
  "見て": "見る",
  "知ります": "知る",
  "知った": "知る",
  "聞きます": "聞く",
  "聞いた": "聞く",
  "聞いて": "聞く",
  "話します": "話す",
  "話した": "話す",
  "話して": "話す",
  "読みます": "読む",
  "読んだ": "読む",
  "読んで": "読む",
  "書きます": "書く",
  "書いた": "書く",
  "書いて": "書く",
  "使います": "使う",
  "使った": "使う",
  "使って": "使う",
  "待ちます": "待つ",
  "待った": "待つ",
  "待って": "待つ",
  "送ります": "送る",
  "送った": "送る",
  "送って": "送る",
  "帰ります": "帰る",
  "帰った": "帰る",
  "帰って": "帰る",
};

// エントリを長い順にソート（長いフレーズを優先マッチ）
export function getSortedKeigoEntries(): [string, KeigoEntry][] {
  return [...keigoDict].sort((a, b) => b[0].length - a[0].length);
}
