export type EmojiCategory =
  | "Smileys"
  | "People"
  | "Animals"
  | "Food"
  | "Travel"
  | "Activities"
  | "Objects"
  | "Symbols";

export interface Emoji {
  emoji: string;
  name: string;
  keywords: string[];
  category: EmojiCategory;
}

export const CATEGORIES: EmojiCategory[] = [
  "Smileys",
  "People",
  "Animals",
  "Food",
  "Travel",
  "Activities",
  "Objects",
  "Symbols",
];

export const EMOJIS: Emoji[] = [
  // Smileys
  { emoji: "😀", name: "grinning face", keywords: ["happy", "smile", "grin"], category: "Smileys" },
  { emoji: "😃", name: "grinning face with big eyes", keywords: ["happy", "smile", "joy"], category: "Smileys" },
  { emoji: "😄", name: "grinning face with smiling eyes", keywords: ["happy", "smile", "laugh"], category: "Smileys" },
  { emoji: "😁", name: "beaming face with smiling eyes", keywords: ["grin", "happy", "smile"], category: "Smileys" },
  { emoji: "😆", name: "grinning squinting face", keywords: ["laugh", "happy", "lol"], category: "Smileys" },
  { emoji: "😅", name: "grinning face with sweat", keywords: ["sweat", "nervous", "laugh"], category: "Smileys" },
  { emoji: "🤣", name: "rolling on the floor laughing", keywords: ["rofl", "lol", "funny", "laugh"], category: "Smileys" },
  { emoji: "😂", name: "face with tears of joy", keywords: ["laugh", "cry", "funny", "lol"], category: "Smileys" },
  { emoji: "🙂", name: "slightly smiling face", keywords: ["smile", "happy"], category: "Smileys" },
  { emoji: "🙃", name: "upside-down face", keywords: ["silly", "sarcasm", "irony"], category: "Smileys" },
  { emoji: "🫠", name: "melting face", keywords: ["melt", "hot", "embarrassed"], category: "Smileys" },
  { emoji: "😉", name: "winking face", keywords: ["wink", "flirt", "joke"], category: "Smileys" },
  { emoji: "😊", name: "smiling face with smiling eyes", keywords: ["blush", "happy", "smile"], category: "Smileys" },
  { emoji: "😇", name: "smiling face with halo", keywords: ["angel", "innocent", "holy"], category: "Smileys" },
  { emoji: "🥰", name: "smiling face with hearts", keywords: ["love", "heart", "adore"], category: "Smileys" },
  { emoji: "😍", name: "smiling face with heart-eyes", keywords: ["love", "crush", "heart"], category: "Smileys" },
  { emoji: "🤩", name: "star-struck", keywords: ["star", "wow", "excited", "celebrity"], category: "Smileys" },
  { emoji: "😘", name: "face blowing a kiss", keywords: ["kiss", "love", "heart"], category: "Smileys" },
  { emoji: "😗", name: "kissing face", keywords: ["kiss", "pout"], category: "Smileys" },
  { emoji: "😚", name: "kissing face with closed eyes", keywords: ["kiss", "love"], category: "Smileys" },
  { emoji: "😙", name: "kissing face with smiling eyes", keywords: ["kiss", "smile"], category: "Smileys" },
  { emoji: "🥲", name: "smiling face with tear", keywords: ["grateful", "relieved", "cry"], category: "Smileys" },
  { emoji: "😋", name: "face savoring food", keywords: ["yum", "delicious", "food"], category: "Smileys" },
  { emoji: "😛", name: "face with tongue", keywords: ["tongue", "playful"], category: "Smileys" },
  { emoji: "😜", name: "winking face with tongue", keywords: ["tongue", "wink", "playful"], category: "Smileys" },
  { emoji: "🤪", name: "zany face", keywords: ["crazy", "wild", "silly"], category: "Smileys" },
  { emoji: "😝", name: "squinting face with tongue", keywords: ["tongue", "gross"], category: "Smileys" },
  { emoji: "🤑", name: "money-mouth face", keywords: ["money", "rich", "greedy"], category: "Smileys" },
  { emoji: "🤗", name: "smiling face with open hands", keywords: ["hug", "warm", "care"], category: "Smileys" },
  { emoji: "🤭", name: "face with hand over mouth", keywords: ["secret", "oops", "giggle"], category: "Smileys" },
  { emoji: "🫢", name: "face with open eyes and hand over mouth", keywords: ["shock", "surprise", "secret"], category: "Smileys" },
  { emoji: "🫣", name: "face with peeking eye", keywords: ["peek", "shy", "hide"], category: "Smileys" },
  { emoji: "🤫", name: "shushing face", keywords: ["quiet", "shh", "secret"], category: "Smileys" },
  { emoji: "🤔", name: "thinking face", keywords: ["think", "wonder", "hmm"], category: "Smileys" },
  { emoji: "🫡", name: "saluting face", keywords: ["salute", "respect", "military"], category: "Smileys" },
  { emoji: "🤐", name: "zipper-mouth face", keywords: ["quiet", "secret", "zip"], category: "Smileys" },
  { emoji: "🤨", name: "face with raised eyebrow", keywords: ["skeptical", "doubt", "suspicious"], category: "Smileys" },
  { emoji: "😐", name: "neutral face", keywords: ["meh", "neutral", "expressionless"], category: "Smileys" },
  { emoji: "😑", name: "expressionless face", keywords: ["blank", "deadpan", "no emotion"], category: "Smileys" },
  { emoji: "😶", name: "face without mouth", keywords: ["silent", "no words", "speechless"], category: "Smileys" },
  { emoji: "🫥", name: "dotted line face", keywords: ["invisible", "hidden", "fade"], category: "Smileys" },
  { emoji: "😶‍🌫️", name: "face in clouds", keywords: ["fog", "confused", "cloud"], category: "Smileys" },
  { emoji: "😏", name: "smirking face", keywords: ["smirk", "smug", "flirt"], category: "Smileys" },
  { emoji: "😒", name: "unamused face", keywords: ["unimpressed", "bored", "meh"], category: "Smileys" },
  { emoji: "🙄", name: "face with rolling eyes", keywords: ["eye roll", "whatever", "bored"], category: "Smileys" },
  { emoji: "😬", name: "grimacing face", keywords: ["grimace", "awkward", "nervous"], category: "Smileys" },
  { emoji: "😮‍💨", name: "face exhaling", keywords: ["sigh", "exhale", "tired"], category: "Smileys" },
  { emoji: "🤥", name: "lying face", keywords: ["liar", "pinocchio", "lie"], category: "Smileys" },
  { emoji: "🫨", name: "shaking face", keywords: ["shake", "no", "tremble"], category: "Smileys" },
  { emoji: "😌", name: "relieved face", keywords: ["relief", "peace", "calm"], category: "Smileys" },
  { emoji: "😔", name: "pensive face", keywords: ["sad", "thoughtful", "pensive"], category: "Smileys" },
  { emoji: "😪", name: "sleepy face", keywords: ["sleep", "tired", "drowsy"], category: "Smileys" },
  { emoji: "🤤", name: "drooling face", keywords: ["drool", "hungry", "desire"], category: "Smileys" },
  { emoji: "😴", name: "sleeping face", keywords: ["sleep", "zzz", "tired", "night"], category: "Smileys" },
  { emoji: "😷", name: "face with medical mask", keywords: ["sick", "mask", "ill", "covid"], category: "Smileys" },
  { emoji: "🤒", name: "face with thermometer", keywords: ["sick", "fever", "ill"], category: "Smileys" },
  { emoji: "🤕", name: "face with head-bandage", keywords: ["hurt", "injured", "bandage"], category: "Smileys" },
  { emoji: "🤢", name: "nauseated face", keywords: ["sick", "nausea", "gross"], category: "Smileys" },
  { emoji: "🤮", name: "face vomiting", keywords: ["vomit", "sick", "puke"], category: "Smileys" },
  { emoji: "🤧", name: "sneezing face", keywords: ["sneeze", "sick", "cold"], category: "Smileys" },
  { emoji: "🥵", name: "hot face", keywords: ["hot", "heat", "sweating"], category: "Smileys" },
  { emoji: "🥶", name: "cold face", keywords: ["cold", "freeze", "ice"], category: "Smileys" },
  { emoji: "🥴", name: "woozy face", keywords: ["drunk", "dizzy", "confused"], category: "Smileys" },
  { emoji: "😵", name: "face with crossed-out eyes", keywords: ["dizzy", "dead", "ko"], category: "Smileys" },
  { emoji: "😵‍💫", name: "face with spiral eyes", keywords: ["dizzy", "hypnotized", "spiral"], category: "Smileys" },
  { emoji: "🤯", name: "exploding head", keywords: ["mind blown", "shocked", "explosion"], category: "Smileys" },
  { emoji: "🤠", name: "cowboy hat face", keywords: ["cowboy", "hat", "western"], category: "Smileys" },
  { emoji: "🥳", name: "partying face", keywords: ["party", "celebrate", "birthday"], category: "Smileys" },
  { emoji: "🥸", name: "disguised face", keywords: ["disguise", "glasses", "incognito"], category: "Smileys" },
  { emoji: "😎", name: "smiling face with sunglasses", keywords: ["cool", "sunglasses", "awesome"], category: "Smileys" },
  { emoji: "🤓", name: "nerd face", keywords: ["nerd", "geek", "glasses"], category: "Smileys" },
  { emoji: "🧐", name: "face with monocle", keywords: ["monocle", "curious", "detective"], category: "Smileys" },
  { emoji: "😕", name: "confused face", keywords: ["confused", "unsure", "puzzled"], category: "Smileys" },
  { emoji: "🫤", name: "face with diagonal mouth", keywords: ["unsure", "meh", "doubtful"], category: "Smileys" },
  { emoji: "😟", name: "worried face", keywords: ["worried", "concerned", "nervous"], category: "Smileys" },
  { emoji: "🙁", name: "slightly frowning face", keywords: ["sad", "frown", "unhappy"], category: "Smileys" },
  { emoji: "☹️", name: "frowning face", keywords: ["sad", "frown", "unhappy"], category: "Smileys" },
  { emoji: "😮", name: "face with open mouth", keywords: ["surprise", "wow", "shock"], category: "Smileys" },
  { emoji: "😯", name: "hushed face", keywords: ["hushed", "surprised", "quiet"], category: "Smileys" },
  { emoji: "😲", name: "astonished face", keywords: ["shocked", "amazed", "wow"], category: "Smileys" },
  { emoji: "😳", name: "flushed face", keywords: ["embarrassed", "blush", "shocked"], category: "Smileys" },
  { emoji: "🥺", name: "pleading face", keywords: ["puppy eyes", "beg", "please"], category: "Smileys" },
  { emoji: "🥹", name: "face holding back tears", keywords: ["touched", "moved", "cry"], category: "Smileys" },
  { emoji: "😦", name: "frowning face with open mouth", keywords: ["frown", "surprised", "anguish"], category: "Smileys" },
  { emoji: "😧", name: "anguished face", keywords: ["anguish", "pain", "distress"], category: "Smileys" },
  { emoji: "😨", name: "fearful face", keywords: ["fear", "scared", "afraid"], category: "Smileys" },
  { emoji: "😰", name: "anxious face with sweat", keywords: ["nervous", "anxiety", "sweat"], category: "Smileys" },
  { emoji: "😥", name: "sad but relieved face", keywords: ["relief", "sad", "sweat"], category: "Smileys" },
  { emoji: "😢", name: "crying face", keywords: ["cry", "tear", "sad"], category: "Smileys" },
  { emoji: "😭", name: "loudly crying face", keywords: ["cry", "sob", "tears", "sad"], category: "Smileys" },
  { emoji: "😱", name: "face screaming in fear", keywords: ["scream", "fear", "horror", "shocked"], category: "Smileys" },
  { emoji: "😖", name: "confounded face", keywords: ["confounded", "frustrated", "stress"], category: "Smileys" },
  { emoji: "😣", name: "persevering face", keywords: ["struggle", "persevere", "hard"], category: "Smileys" },
  { emoji: "😞", name: "disappointed face", keywords: ["disappointed", "sad", "letdown"], category: "Smileys" },
  { emoji: "😓", name: "downcast face with sweat", keywords: ["hard work", "tired", "sweat"], category: "Smileys" },
  { emoji: "😩", name: "weary face", keywords: ["weary", "tired", "exhausted"], category: "Smileys" },
  { emoji: "😫", name: "tired face", keywords: ["tired", "exhausted", "weary"], category: "Smileys" },
  { emoji: "🥱", name: "yawning face", keywords: ["yawn", "tired", "bored"], category: "Smileys" },
  { emoji: "😤", name: "face with steam from nose", keywords: ["proud", "angry", "steam"], category: "Smileys" },
  { emoji: "😡", name: "enraged face", keywords: ["angry", "rage", "mad"], category: "Smileys" },
  { emoji: "😠", name: "angry face", keywords: ["angry", "mad", "grumpy"], category: "Smileys" },
  { emoji: "🤬", name: "face with symbols on mouth", keywords: ["swear", "cursing", "angry"], category: "Smileys" },
  { emoji: "😈", name: "smiling face with horns", keywords: ["devil", "evil", "bad"], category: "Smileys" },
  { emoji: "👿", name: "angry face with horns", keywords: ["devil", "evil", "angry"], category: "Smileys" },
  { emoji: "💀", name: "skull", keywords: ["death", "dead", "skull", "scary"], category: "Smileys" },
  { emoji: "☠️", name: "skull and crossbones", keywords: ["danger", "poison", "dead"], category: "Smileys" },
  { emoji: "💩", name: "pile of poo", keywords: ["poop", "crap", "funny"], category: "Smileys" },
  { emoji: "🤡", name: "clown face", keywords: ["clown", "funny", "circus"], category: "Smileys" },
  { emoji: "👹", name: "ogre", keywords: ["monster", "ogre", "demon"], category: "Smileys" },
  { emoji: "👺", name: "goblin", keywords: ["goblin", "tengu", "monster"], category: "Smileys" },
  { emoji: "👻", name: "ghost", keywords: ["ghost", "spirit", "halloween", "boo"], category: "Smileys" },
  { emoji: "👽", name: "alien", keywords: ["alien", "ufo", "space"], category: "Smileys" },
  { emoji: "👾", name: "alien monster", keywords: ["alien", "game", "retro", "space"], category: "Smileys" },
  { emoji: "🤖", name: "robot", keywords: ["robot", "bot", "ai", "machine"], category: "Smileys" },
  { emoji: "😺", name: "grinning cat", keywords: ["cat", "happy", "smile"], category: "Smileys" },
  { emoji: "😸", name: "grinning cat with smiling eyes", keywords: ["cat", "laugh", "happy"], category: "Smileys" },
  { emoji: "😹", name: "cat with tears of joy", keywords: ["cat", "laugh", "funny"], category: "Smileys" },
  { emoji: "😻", name: "smiling cat with heart-eyes", keywords: ["cat", "love", "heart"], category: "Smileys" },
  { emoji: "😼", name: "cat with wry smile", keywords: ["cat", "smirk", "sly"], category: "Smileys" },
  { emoji: "😽", name: "kissing cat", keywords: ["cat", "kiss"], category: "Smileys" },
  { emoji: "🙀", name: "weary cat", keywords: ["cat", "shocked", "scared"], category: "Smileys" },
  { emoji: "😿", name: "crying cat", keywords: ["cat", "sad", "cry"], category: "Smileys" },
  { emoji: "😾", name: "pouting cat", keywords: ["cat", "angry", "grumpy"], category: "Smileys" },

  // People
  { emoji: "👋", name: "waving hand", keywords: ["wave", "hello", "hi", "bye"], category: "People" },
  { emoji: "🤚", name: "raised back of hand", keywords: ["hand", "raise", "stop"], category: "People" },
  { emoji: "🖐️", name: "hand with fingers splayed", keywords: ["hand", "five", "high five"], category: "People" },
  { emoji: "✋", name: "raised hand", keywords: ["hand", "stop", "raise"], category: "People" },
  { emoji: "🖖", name: "vulcan salute", keywords: ["spock", "star trek", "vulcan"], category: "People" },
  { emoji: "🫱", name: "rightwards hand", keywords: ["hand", "right"], category: "People" },
  { emoji: "🫲", name: "leftwards hand", keywords: ["hand", "left"], category: "People" },
  { emoji: "🫳", name: "palm down hand", keywords: ["hand", "down"], category: "People" },
  { emoji: "🫴", name: "palm up hand", keywords: ["hand", "up", "offer"], category: "People" },
  { emoji: "👌", name: "ok hand", keywords: ["ok", "perfect", "agree"], category: "People" },
  { emoji: "🤌", name: "pinched fingers", keywords: ["italian", "perfect", "chef kiss"], category: "People" },
  { emoji: "🤏", name: "pinching hand", keywords: ["small", "little", "tiny"], category: "People" },
  { emoji: "✌️", name: "victory hand", keywords: ["peace", "victory", "two", "fingers"], category: "People" },
  { emoji: "🤞", name: "crossed fingers", keywords: ["luck", "hope", "cross"], category: "People" },
  { emoji: "🫰", name: "hand with index finger and thumb crossed", keywords: ["snap", "money", "love"], category: "People" },
  { emoji: "🤟", name: "love-you gesture", keywords: ["love", "sign language", "rock"], category: "People" },
  { emoji: "🤘", name: "sign of the horns", keywords: ["rock", "metal", "devil", "horns"], category: "People" },
  { emoji: "🤙", name: "call me hand", keywords: ["call", "shaka", "phone"], category: "People" },
  { emoji: "👈", name: "backhand index pointing left", keywords: ["left", "point", "direction"], category: "People" },
  { emoji: "👉", name: "backhand index pointing right", keywords: ["right", "point", "direction"], category: "People" },
  { emoji: "👆", name: "backhand index pointing up", keywords: ["up", "point", "above"], category: "People" },
  { emoji: "🖕", name: "middle finger", keywords: ["middle finger", "rude", "offensive"], category: "People" },
  { emoji: "👇", name: "backhand index pointing down", keywords: ["down", "point", "below"], category: "People" },
  { emoji: "☝️", name: "index pointing up", keywords: ["up", "point", "finger"], category: "People" },
  { emoji: "🫵", name: "index pointing at the viewer", keywords: ["you", "point", "finger"], category: "People" },
  { emoji: "👍", name: "thumbs up", keywords: ["like", "approve", "yes", "good"], category: "People" },
  { emoji: "👎", name: "thumbs down", keywords: ["dislike", "no", "bad", "disapprove"], category: "People" },
  { emoji: "✊", name: "raised fist", keywords: ["fist", "power", "fight"], category: "People" },
  { emoji: "👊", name: "oncoming fist", keywords: ["punch", "fist", "fight"], category: "People" },
  { emoji: "🤛", name: "left-facing fist", keywords: ["fist bump", "left"], category: "People" },
  { emoji: "🤜", name: "right-facing fist", keywords: ["fist bump", "right"], category: "People" },
  { emoji: "👏", name: "clapping hands", keywords: ["clap", "applause", "bravo"], category: "People" },
  { emoji: "🙌", name: "raising hands", keywords: ["celebrate", "raise", "hooray"], category: "People" },
  { emoji: "🫶", name: "heart hands", keywords: ["love", "heart", "hands"], category: "People" },
  { emoji: "👐", name: "open hands", keywords: ["open", "hug", "receive"], category: "People" },
  { emoji: "🤲", name: "palms up together", keywords: ["pray", "ask", "palms"], category: "People" },
  { emoji: "🤝", name: "handshake", keywords: ["deal", "agree", "shake hands"], category: "People" },
  { emoji: "🙏", name: "folded hands", keywords: ["pray", "please", "thank you", "namaste"], category: "People" },
  { emoji: "✍️", name: "writing hand", keywords: ["write", "pen", "sign"], category: "People" },
  { emoji: "💅", name: "nail polish", keywords: ["nails", "beauty", "manicure"], category: "People" },
  { emoji: "🤳", name: "selfie", keywords: ["selfie", "photo", "camera"], category: "People" },
  { emoji: "💪", name: "flexed biceps", keywords: ["muscle", "strong", "flex", "gym"], category: "People" },
  { emoji: "🦾", name: "mechanical arm", keywords: ["robot", "prosthetic", "cyborg"], category: "People" },
  { emoji: "🦵", name: "leg", keywords: ["leg", "kick", "limb"], category: "People" },
  { emoji: "🦶", name: "foot", keywords: ["foot", "kick", "toe"], category: "People" },
  { emoji: "👂", name: "ear", keywords: ["ear", "hear", "listen"], category: "People" },
  { emoji: "🦻", name: "ear with hearing aid", keywords: ["hearing", "deaf", "aid"], category: "People" },
  { emoji: "👃", name: "nose", keywords: ["nose", "smell", "sniff"], category: "People" },
  { emoji: "🧠", name: "brain", keywords: ["brain", "think", "smart", "mind"], category: "People" },
  { emoji: "🫀", name: "anatomical heart", keywords: ["heart", "organ", "medical"], category: "People" },
  { emoji: "🫁", name: "lungs", keywords: ["lungs", "breathe", "organ"], category: "People" },
  { emoji: "🦷", name: "tooth", keywords: ["tooth", "dental", "teeth"], category: "People" },
  { emoji: "🦴", name: "bone", keywords: ["bone", "skeleton", "dog"], category: "People" },
  { emoji: "👀", name: "eyes", keywords: ["eyes", "look", "see", "watch"], category: "People" },
  { emoji: "👁️", name: "eye", keywords: ["eye", "look", "see"], category: "People" },
  { emoji: "👅", name: "tongue", keywords: ["tongue", "taste", "lick"], category: "People" },
  { emoji: "👄", name: "mouth", keywords: ["mouth", "lips", "kiss"], category: "People" },
  { emoji: "🫦", name: "biting lip", keywords: ["lip bite", "sexy", "nervous"], category: "People" },
  { emoji: "👶", name: "baby", keywords: ["baby", "infant", "child"], category: "People" },
  { emoji: "🧒", name: "child", keywords: ["child", "kid", "young"], category: "People" },
  { emoji: "👦", name: "boy", keywords: ["boy", "male", "child"], category: "People" },
  { emoji: "👧", name: "girl", keywords: ["girl", "female", "child"], category: "People" },
  { emoji: "🧑", name: "person", keywords: ["person", "adult", "human"], category: "People" },
  { emoji: "👱", name: "person blond hair", keywords: ["blond", "blonde", "hair"], category: "People" },
  { emoji: "👨", name: "man", keywords: ["man", "male", "person"], category: "People" },
  { emoji: "🧔", name: "person beard", keywords: ["beard", "facial hair"], category: "People" },
  { emoji: "👩", name: "woman", keywords: ["woman", "female", "person"], category: "People" },
  { emoji: "🧓", name: "older person", keywords: ["old", "elder", "senior"], category: "People" },
  { emoji: "👴", name: "old man", keywords: ["old", "grandpa", "senior"], category: "People" },
  { emoji: "👵", name: "old woman", keywords: ["old", "grandma", "senior"], category: "People" },
  { emoji: "🙍", name: "person frowning", keywords: ["frown", "sad", "unhappy"], category: "People" },
  { emoji: "🙎", name: "person pouting", keywords: ["pout", "angry", "upset"], category: "People" },
  { emoji: "🙅", name: "person gesturing no", keywords: ["no", "stop", "refuse"], category: "People" },
  { emoji: "🙆", name: "person gesturing ok", keywords: ["ok", "yes", "agree"], category: "People" },
  { emoji: "💁", name: "person tipping hand", keywords: ["info", "help", "sassy"], category: "People" },
  { emoji: "🙋", name: "person raising hand", keywords: ["raise hand", "question", "hello"], category: "People" },
  { emoji: "🧏", name: "deaf person", keywords: ["deaf", "hearing", "sign language"], category: "People" },
  { emoji: "🙇", name: "person bowing", keywords: ["bow", "sorry", "respect"], category: "People" },
  { emoji: "🤦", name: "person facepalming", keywords: ["facepalm", "embarrassed", "duh"], category: "People" },
  { emoji: "🤷", name: "person shrugging", keywords: ["shrug", "idk", "whatever"], category: "People" },
  { emoji: "👮", name: "police officer", keywords: ["police", "cop", "officer", "law"], category: "People" },
  { emoji: "🕵️", name: "detective", keywords: ["detective", "spy", "investigate"], category: "People" },
  { emoji: "💂", name: "guard", keywords: ["guard", "soldier", "uk"], category: "People" },
  { emoji: "🥷", name: "ninja", keywords: ["ninja", "stealth", "martial arts"], category: "People" },
  { emoji: "👷", name: "construction worker", keywords: ["construction", "worker", "helmet"], category: "People" },
  { emoji: "🫅", name: "person with crown", keywords: ["royalty", "crown", "noble"], category: "People" },
  { emoji: "🤴", name: "prince", keywords: ["prince", "royal", "crown"], category: "People" },
  { emoji: "👸", name: "princess", keywords: ["princess", "royal", "crown"], category: "People" },
  { emoji: "👳", name: "person wearing turban", keywords: ["turban", "sikh", "muslim"], category: "People" },
  { emoji: "👲", name: "person with skullcap", keywords: ["chinese", "hat", "gua pi mao"], category: "People" },
  { emoji: "🧕", name: "woman with headscarf", keywords: ["hijab", "headscarf", "muslim"], category: "People" },
  { emoji: "🤵", name: "person in tuxedo", keywords: ["tuxedo", "groom", "wedding", "formal"], category: "People" },
  { emoji: "👰", name: "person with veil", keywords: ["bride", "wedding", "veil"], category: "People" },
  { emoji: "🤰", name: "pregnant woman", keywords: ["pregnant", "baby", "expecting"], category: "People" },
  { emoji: "🫃", name: "pregnant man", keywords: ["pregnant", "baby", "expecting"], category: "People" },
  { emoji: "🤱", name: "breast-feeding", keywords: ["breastfeed", "baby", "mother"], category: "People" },
  { emoji: "👼", name: "baby angel", keywords: ["angel", "baby", "innocent"], category: "People" },
  { emoji: "🎅", name: "santa claus", keywords: ["santa", "christmas", "holiday"], category: "People" },
  { emoji: "🤶", name: "mrs claus", keywords: ["mrs claus", "christmas", "holiday"], category: "People" },
  { emoji: "🧙", name: "mage", keywords: ["wizard", "witch", "magic", "sorcerer"], category: "People" },
  { emoji: "🧝", name: "elf", keywords: ["elf", "fantasy", "christmas"], category: "People" },
  { emoji: "🧛", name: "vampire", keywords: ["vampire", "dracula", "halloween"], category: "People" },
  { emoji: "🧟", name: "zombie", keywords: ["zombie", "undead", "halloween"], category: "People" },
  { emoji: "🧞", name: "genie", keywords: ["genie", "magic", "wish"], category: "People" },
  { emoji: "🧜", name: "merperson", keywords: ["mermaid", "merman", "fantasy", "sea"], category: "People" },
  { emoji: "🧚", name: "fairy", keywords: ["fairy", "magic", "fantasy", "wings"], category: "People" },
  { emoji: "🧌", name: "troll", keywords: ["troll", "fantasy", "monster"], category: "People" },
  { emoji: "👫", name: "woman and man holding hands", keywords: ["couple", "love", "together"], category: "People" },
  { emoji: "👬", name: "men holding hands", keywords: ["couple", "gay", "together"], category: "People" },
  { emoji: "👭", name: "women holding hands", keywords: ["couple", "lesbian", "together"], category: "People" },
  { emoji: "💏", name: "kiss", keywords: ["kiss", "love", "couple"], category: "People" },
  { emoji: "💑", name: "couple with heart", keywords: ["love", "couple", "romance"], category: "People" },
  { emoji: "👪", name: "family", keywords: ["family", "home", "parents", "children"], category: "People" },

  // Animals
  { emoji: "🐶", name: "dog face", keywords: ["dog", "puppy", "pet"], category: "Animals" },
  { emoji: "🐱", name: "cat face", keywords: ["cat", "kitten", "pet"], category: "Animals" },
  { emoji: "🐭", name: "mouse face", keywords: ["mouse", "rodent", "small"], category: "Animals" },
  { emoji: "🐹", name: "hamster", keywords: ["hamster", "pet", "rodent"], category: "Animals" },
  { emoji: "🐰", name: "rabbit face", keywords: ["rabbit", "bunny", "easter"], category: "Animals" },
  { emoji: "🦊", name: "fox", keywords: ["fox", "sly", "orange"], category: "Animals" },
  { emoji: "🐻", name: "bear", keywords: ["bear", "animal", "teddy"], category: "Animals" },
  { emoji: "🐼", name: "panda", keywords: ["panda", "china", "bamboo"], category: "Animals" },
  { emoji: "🐻‍❄️", name: "polar bear", keywords: ["polar bear", "arctic", "white"], category: "Animals" },
  { emoji: "🐨", name: "koala", keywords: ["koala", "australia", "marsupial"], category: "Animals" },
  { emoji: "🐯", name: "tiger face", keywords: ["tiger", "wild", "stripes"], category: "Animals" },
  { emoji: "🦁", name: "lion", keywords: ["lion", "king", "wild", "mane"], category: "Animals" },
  { emoji: "🐮", name: "cow face", keywords: ["cow", "moo", "farm"], category: "Animals" },
  { emoji: "🐷", name: "pig face", keywords: ["pig", "oink", "farm"], category: "Animals" },
  { emoji: "🐸", name: "frog", keywords: ["frog", "green", "ribbit"], category: "Animals" },
  { emoji: "🐵", name: "monkey face", keywords: ["monkey", "ape", "banana"], category: "Animals" },
  { emoji: "🙈", name: "see-no-evil monkey", keywords: ["monkey", "see no evil", "shy"], category: "Animals" },
  { emoji: "🙉", name: "hear-no-evil monkey", keywords: ["monkey", "hear no evil"], category: "Animals" },
  { emoji: "🙊", name: "speak-no-evil monkey", keywords: ["monkey", "speak no evil"], category: "Animals" },
  { emoji: "🐔", name: "chicken", keywords: ["chicken", "bird", "farm"], category: "Animals" },
  { emoji: "🐧", name: "penguin", keywords: ["penguin", "arctic", "linux"], category: "Animals" },
  { emoji: "🐦", name: "bird", keywords: ["bird", "tweet", "fly"], category: "Animals" },
  { emoji: "🐤", name: "baby chick", keywords: ["chick", "baby", "bird", "yellow"], category: "Animals" },
  { emoji: "🦆", name: "duck", keywords: ["duck", "quack", "water"], category: "Animals" },
  { emoji: "🦅", name: "eagle", keywords: ["eagle", "bird", "freedom", "usa"], category: "Animals" },
  { emoji: "🦉", name: "owl", keywords: ["owl", "wise", "night", "bird"], category: "Animals" },
  { emoji: "🦇", name: "bat", keywords: ["bat", "halloween", "night", "vampire"], category: "Animals" },
  { emoji: "🐺", name: "wolf", keywords: ["wolf", "howl", "wild"], category: "Animals" },
  { emoji: "🐗", name: "boar", keywords: ["boar", "pig", "wild"], category: "Animals" },
  { emoji: "🐴", name: "horse face", keywords: ["horse", "pony", "animal"], category: "Animals" },
  { emoji: "🦄", name: "unicorn", keywords: ["unicorn", "magic", "rainbow", "fantasy"], category: "Animals" },
  { emoji: "🐝", name: "honeybee", keywords: ["bee", "honey", "sting", "insect"], category: "Animals" },
  { emoji: "🪱", name: "worm", keywords: ["worm", "earth", "dirt"], category: "Animals" },
  { emoji: "🐛", name: "bug", keywords: ["bug", "caterpillar", "insect"], category: "Animals" },
  { emoji: "🦋", name: "butterfly", keywords: ["butterfly", "beautiful", "nature"], category: "Animals" },
  { emoji: "🐌", name: "snail", keywords: ["snail", "slow", "shell"], category: "Animals" },
  { emoji: "🐞", name: "lady beetle", keywords: ["ladybug", "insect", "red"], category: "Animals" },
  { emoji: "🐜", name: "ant", keywords: ["ant", "insect", "colony"], category: "Animals" },
  { emoji: "🪲", name: "beetle", keywords: ["beetle", "bug", "insect"], category: "Animals" },
  { emoji: "🦟", name: "mosquito", keywords: ["mosquito", "bite", "insect"], category: "Animals" },
  { emoji: "🦗", name: "cricket", keywords: ["cricket", "insect", "chirp"], category: "Animals" },
  { emoji: "🪳", name: "cockroach", keywords: ["cockroach", "bug", "gross"], category: "Animals" },
  { emoji: "🕷️", name: "spider", keywords: ["spider", "web", "scary"], category: "Animals" },
  { emoji: "🦂", name: "scorpion", keywords: ["scorpion", "sting", "dangerous"], category: "Animals" },
  { emoji: "🐢", name: "turtle", keywords: ["turtle", "slow", "shell", "sea"], category: "Animals" },
  { emoji: "🐍", name: "snake", keywords: ["snake", "serpent", "hiss"], category: "Animals" },
  { emoji: "🦎", name: "lizard", keywords: ["lizard", "reptile", "gecko"], category: "Animals" },
  { emoji: "🦖", name: "t-rex", keywords: ["dinosaur", "t-rex", "jurassic"], category: "Animals" },
  { emoji: "🦕", name: "sauropod", keywords: ["dinosaur", "brachiosaurus", "jurassic"], category: "Animals" },
  { emoji: "🐊", name: "crocodile", keywords: ["crocodile", "alligator", "reptile"], category: "Animals" },
  { emoji: "🐋", name: "whale", keywords: ["whale", "ocean", "sea", "blue"], category: "Animals" },
  { emoji: "🐬", name: "dolphin", keywords: ["dolphin", "ocean", "sea", "smart"], category: "Animals" },
  { emoji: "🦭", name: "seal", keywords: ["seal", "ocean", "sea", "arctic"], category: "Animals" },
  { emoji: "🐟", name: "fish", keywords: ["fish", "ocean", "sea", "aquarium"], category: "Animals" },
  { emoji: "🐠", name: "tropical fish", keywords: ["fish", "tropical", "colorful"], category: "Animals" },
  { emoji: "🐡", name: "blowfish", keywords: ["blowfish", "puffer", "spiky"], category: "Animals" },
  { emoji: "🦈", name: "shark", keywords: ["shark", "ocean", "danger", "jaws"], category: "Animals" },
  { emoji: "🐙", name: "octopus", keywords: ["octopus", "tentacles", "sea"], category: "Animals" },
  { emoji: "🐚", name: "spiral shell", keywords: ["shell", "snail", "ocean"], category: "Animals" },
  { emoji: "🪸", name: "coral", keywords: ["coral", "ocean", "reef"], category: "Animals" },
  { emoji: "🐌", name: "snail", keywords: ["snail", "slow", "shell"], category: "Animals" },
  { emoji: "🦞", name: "lobster", keywords: ["lobster", "seafood", "red"], category: "Animals" },
  { emoji: "🦀", name: "crab", keywords: ["crab", "seafood", "sideways"], category: "Animals" },
  { emoji: "🦐", name: "shrimp", keywords: ["shrimp", "seafood", "small"], category: "Animals" },
  { emoji: "🦑", name: "squid", keywords: ["squid", "tentacles", "ink"], category: "Animals" },
  { emoji: "🦪", name: "oyster", keywords: ["oyster", "pearl", "seafood"], category: "Animals" },
  { emoji: "🌸", name: "cherry blossom", keywords: ["flower", "pink", "japan", "spring"], category: "Animals" },
  { emoji: "🌿", name: "herb", keywords: ["herb", "plant", "green", "leaf"], category: "Animals" },
  { emoji: "🌲", name: "evergreen tree", keywords: ["tree", "forest", "pine"], category: "Animals" },
  { emoji: "🌳", name: "deciduous tree", keywords: ["tree", "oak", "forest"], category: "Animals" },
  { emoji: "🌴", name: "palm tree", keywords: ["palm", "tropical", "beach"], category: "Animals" },
  { emoji: "🌵", name: "cactus", keywords: ["cactus", "desert", "spiky"], category: "Animals" },
  { emoji: "🐾", name: "paw prints", keywords: ["paw", "dog", "cat", "footprint"], category: "Animals" },

  // Food
  { emoji: "🍎", name: "red apple", keywords: ["apple", "fruit", "red"], category: "Food" },
  { emoji: "🍐", name: "pear", keywords: ["pear", "fruit", "green"], category: "Food" },
  { emoji: "🍊", name: "tangerine", keywords: ["orange", "citrus", "fruit"], category: "Food" },
  { emoji: "🍋", name: "lemon", keywords: ["lemon", "citrus", "sour", "yellow"], category: "Food" },
  { emoji: "🍌", name: "banana", keywords: ["banana", "fruit", "yellow"], category: "Food" },
  { emoji: "🍉", name: "watermelon", keywords: ["watermelon", "summer", "fruit"], category: "Food" },
  { emoji: "🍇", name: "grapes", keywords: ["grapes", "wine", "fruit", "purple"], category: "Food" },
  { emoji: "🍓", name: "strawberry", keywords: ["strawberry", "fruit", "red", "sweet"], category: "Food" },
  { emoji: "🫐", name: "blueberries", keywords: ["blueberry", "fruit", "blue"], category: "Food" },
  { emoji: "🍈", name: "melon", keywords: ["melon", "fruit", "sweet"], category: "Food" },
  { emoji: "🍒", name: "cherries", keywords: ["cherry", "fruit", "red"], category: "Food" },
  { emoji: "🍑", name: "peach", keywords: ["peach", "fruit", "fuzzy"], category: "Food" },
  { emoji: "🥭", name: "mango", keywords: ["mango", "tropical", "fruit"], category: "Food" },
  { emoji: "🍍", name: "pineapple", keywords: ["pineapple", "tropical", "fruit"], category: "Food" },
  { emoji: "🥥", name: "coconut", keywords: ["coconut", "tropical", "fruit"], category: "Food" },
  { emoji: "🥝", name: "kiwi fruit", keywords: ["kiwi", "fruit", "green"], category: "Food" },
  { emoji: "🍅", name: "tomato", keywords: ["tomato", "red", "vegetable", "fruit"], category: "Food" },
  { emoji: "🫒", name: "olive", keywords: ["olive", "green", "mediterranean"], category: "Food" },
  { emoji: "🥑", name: "avocado", keywords: ["avocado", "guacamole", "green"], category: "Food" },
  { emoji: "🍆", name: "eggplant", keywords: ["eggplant", "aubergine", "purple"], category: "Food" },
  { emoji: "🥔", name: "potato", keywords: ["potato", "vegetable", "starchy"], category: "Food" },
  { emoji: "🥕", name: "carrot", keywords: ["carrot", "orange", "vegetable"], category: "Food" },
  { emoji: "🌽", name: "ear of corn", keywords: ["corn", "maize", "yellow"], category: "Food" },
  { emoji: "🌶️", name: "hot pepper", keywords: ["pepper", "spicy", "hot", "chili"], category: "Food" },
  { emoji: "🫑", name: "bell pepper", keywords: ["pepper", "vegetable", "colorful"], category: "Food" },
  { emoji: "🥒", name: "cucumber", keywords: ["cucumber", "vegetable", "green"], category: "Food" },
  { emoji: "🥬", name: "leafy green", keywords: ["salad", "vegetable", "green", "kale"], category: "Food" },
  { emoji: "🥦", name: "broccoli", keywords: ["broccoli", "vegetable", "green", "tree"], category: "Food" },
  { emoji: "🧄", name: "garlic", keywords: ["garlic", "spice", "cooking"], category: "Food" },
  { emoji: "🧅", name: "onion", keywords: ["onion", "vegetable", "tears"], category: "Food" },
  { emoji: "🍄", name: "mushroom", keywords: ["mushroom", "fungi", "mario"], category: "Food" },
  { emoji: "🥜", name: "peanuts", keywords: ["peanut", "nut", "snack"], category: "Food" },
  { emoji: "🫘", name: "beans", keywords: ["beans", "legume", "protein"], category: "Food" },
  { emoji: "🌰", name: "chestnut", keywords: ["chestnut", "nut", "autumn"], category: "Food" },
  { emoji: "🍞", name: "bread", keywords: ["bread", "loaf", "bakery", "toast"], category: "Food" },
  { emoji: "🥐", name: "croissant", keywords: ["croissant", "french", "pastry", "breakfast"], category: "Food" },
  { emoji: "🥖", name: "baguette bread", keywords: ["baguette", "french", "bread"], category: "Food" },
  { emoji: "🫓", name: "flatbread", keywords: ["flatbread", "pita", "bread"], category: "Food" },
  { emoji: "🥨", name: "pretzel", keywords: ["pretzel", "snack", "german"], category: "Food" },
  { emoji: "🥯", name: "bagel", keywords: ["bagel", "bread", "breakfast"], category: "Food" },
  { emoji: "🧀", name: "cheese wedge", keywords: ["cheese", "dairy", "cheddar"], category: "Food" },
  { emoji: "🍖", name: "meat on bone", keywords: ["meat", "bone", "protein"], category: "Food" },
  { emoji: "🍗", name: "poultry leg", keywords: ["chicken", "turkey", "meat"], category: "Food" },
  { emoji: "🥩", name: "cut of meat", keywords: ["steak", "meat", "beef"], category: "Food" },
  { emoji: "🥚", name: "egg", keywords: ["egg", "breakfast", "protein"], category: "Food" },
  { emoji: "🍳", name: "cooking", keywords: ["frying", "egg", "pan", "cook"], category: "Food" },
  { emoji: "🧈", name: "butter", keywords: ["butter", "dairy", "cooking"], category: "Food" },
  { emoji: "🥞", name: "pancakes", keywords: ["pancakes", "breakfast", "syrup"], category: "Food" },
  { emoji: "🧇", name: "waffle", keywords: ["waffle", "breakfast", "syrup"], category: "Food" },
  { emoji: "🍔", name: "hamburger", keywords: ["burger", "fast food", "beef"], category: "Food" },
  { emoji: "🍟", name: "french fries", keywords: ["fries", "chips", "fast food"], category: "Food" },
  { emoji: "🍕", name: "pizza", keywords: ["pizza", "italian", "cheese"], category: "Food" },
  { emoji: "🌭", name: "hot dog", keywords: ["hot dog", "sausage", "fast food"], category: "Food" },
  { emoji: "🥪", name: "sandwich", keywords: ["sandwich", "sub", "lunch"], category: "Food" },
  { emoji: "🌮", name: "taco", keywords: ["taco", "mexican", "food"], category: "Food" },
  { emoji: "🌯", name: "burrito", keywords: ["burrito", "mexican", "wrap"], category: "Food" },
  { emoji: "🫔", name: "tamale", keywords: ["tamale", "mexican", "corn"], category: "Food" },
  { emoji: "🥙", name: "stuffed flatbread", keywords: ["falafel", "pita", "middle eastern"], category: "Food" },
  { emoji: "🧆", name: "falafel", keywords: ["falafel", "chickpea", "middle eastern"], category: "Food" },
  { emoji: "🍜", name: "steaming bowl", keywords: ["noodles", "ramen", "soup"], category: "Food" },
  { emoji: "🍝", name: "spaghetti", keywords: ["pasta", "spaghetti", "italian"], category: "Food" },
  { emoji: "🍛", name: "curry rice", keywords: ["curry", "indian", "rice"], category: "Food" },
  { emoji: "🍲", name: "pot of food", keywords: ["stew", "soup", "hot pot"], category: "Food" },
  { emoji: "🍣", name: "sushi", keywords: ["sushi", "japanese", "fish", "rice"], category: "Food" },
  { emoji: "🍱", name: "bento box", keywords: ["bento", "japanese", "lunch box"], category: "Food" },
  { emoji: "🍤", name: "fried shrimp", keywords: ["shrimp", "fried", "seafood"], category: "Food" },
  { emoji: "🍙", name: "rice ball", keywords: ["onigiri", "japanese", "rice"], category: "Food" },
  { emoji: "🍘", name: "rice cracker", keywords: ["rice cracker", "japanese", "snack"], category: "Food" },
  { emoji: "🍥", name: "fish cake with swirl", keywords: ["narutomaki", "japanese", "ramen"], category: "Food" },
  { emoji: "🥮", name: "moon cake", keywords: ["mooncake", "chinese", "festival"], category: "Food" },
  { emoji: "🍢", name: "oden", keywords: ["oden", "japanese", "stick"], category: "Food" },
  { emoji: "🍡", name: "dango", keywords: ["dango", "japanese", "sweets"], category: "Food" },
  { emoji: "🍧", name: "shaved ice", keywords: ["shaved ice", "dessert", "summer"], category: "Food" },
  { emoji: "🍨", name: "ice cream", keywords: ["ice cream", "dessert", "cold"], category: "Food" },
  { emoji: "🍦", name: "soft ice cream", keywords: ["soft serve", "ice cream", "cone"], category: "Food" },
  { emoji: "🥧", name: "pie", keywords: ["pie", "dessert", "baked"], category: "Food" },
  { emoji: "🧁", name: "cupcake", keywords: ["cupcake", "dessert", "sweet"], category: "Food" },
  { emoji: "🍰", name: "shortcake", keywords: ["cake", "dessert", "slice"], category: "Food" },
  { emoji: "🎂", name: "birthday cake", keywords: ["birthday", "cake", "candle", "celebrate"], category: "Food" },
  { emoji: "🍮", name: "custard", keywords: ["custard", "pudding", "dessert"], category: "Food" },
  { emoji: "🍭", name: "lollipop", keywords: ["lollipop", "candy", "sweet"], category: "Food" },
  { emoji: "🍬", name: "candy", keywords: ["candy", "sweet", "sugar"], category: "Food" },
  { emoji: "🍫", name: "chocolate bar", keywords: ["chocolate", "sweet", "cocoa"], category: "Food" },
  { emoji: "🍿", name: "popcorn", keywords: ["popcorn", "movie", "cinema", "snack"], category: "Food" },
  { emoji: "🍩", name: "doughnut", keywords: ["donut", "doughnut", "dessert", "sweet"], category: "Food" },
  { emoji: "🍪", name: "cookie", keywords: ["cookie", "biscuit", "sweet", "baked"], category: "Food" },
  { emoji: "☕", name: "hot beverage", keywords: ["coffee", "tea", "hot", "drink"], category: "Food" },
  { emoji: "🫖", name: "teapot", keywords: ["tea", "teapot", "hot", "drink"], category: "Food" },
  { emoji: "🍵", name: "teacup without handle", keywords: ["tea", "green tea", "matcha"], category: "Food" },
  { emoji: "🧃", name: "beverage box", keywords: ["juice", "drink", "box", "straw"], category: "Food" },
  { emoji: "🥤", name: "cup with straw", keywords: ["drink", "straw", "soda"], category: "Food" },
  { emoji: "🧋", name: "bubble tea", keywords: ["bubble tea", "boba", "taiwan", "tea"], category: "Food" },
  { emoji: "🍺", name: "beer mug", keywords: ["beer", "drink", "pub"], category: "Food" },
  { emoji: "🍻", name: "clinking beer mugs", keywords: ["beer", "cheers", "pub"], category: "Food" },
  { emoji: "🥂", name: "clinking glasses", keywords: ["champagne", "cheers", "celebrate"], category: "Food" },
  { emoji: "🍷", name: "wine glass", keywords: ["wine", "drink", "elegant"], category: "Food" },
  { emoji: "🥃", name: "tumbler glass", keywords: ["whiskey", "glass", "drink"], category: "Food" },
  { emoji: "🍸", name: "cocktail glass", keywords: ["cocktail", "martini", "drink"], category: "Food" },
  { emoji: "🍹", name: "tropical drink", keywords: ["cocktail", "tropical", "drink"], category: "Food" },
  { emoji: "🧉", name: "mate", keywords: ["mate", "drink", "south american"], category: "Food" },
  { emoji: "🍾", name: "bottle with popping cork", keywords: ["champagne", "celebrate", "bottle"], category: "Food" },
  { emoji: "🧊", name: "ice", keywords: ["ice", "cold", "frozen", "cube"], category: "Food" },
  { emoji: "🥄", name: "spoon", keywords: ["spoon", "utensil", "eat"], category: "Food" },
  { emoji: "🍴", name: "fork and knife", keywords: ["fork", "knife", "utensil", "eat"], category: "Food" },
  { emoji: "🫙", name: "jar", keywords: ["jar", "container", "preserve"], category: "Food" },

  // Travel
  { emoji: "🚗", name: "automobile", keywords: ["car", "drive", "vehicle"], category: "Travel" },
  { emoji: "🚕", name: "taxi", keywords: ["taxi", "cab", "yellow", "ride"], category: "Travel" },
  { emoji: "🚙", name: "sport utility vehicle", keywords: ["suv", "car", "vehicle"], category: "Travel" },
  { emoji: "🚌", name: "bus", keywords: ["bus", "public transport", "commute"], category: "Travel" },
  { emoji: "🚎", name: "trolleybus", keywords: ["trolley", "bus", "transport"], category: "Travel" },
  { emoji: "🏎️", name: "racing car", keywords: ["race", "car", "fast", "formula"], category: "Travel" },
  { emoji: "🚓", name: "police car", keywords: ["police", "cop", "car", "siren"], category: "Travel" },
  { emoji: "🚑", name: "ambulance", keywords: ["ambulance", "emergency", "medical"], category: "Travel" },
  { emoji: "🚒", name: "fire engine", keywords: ["fire truck", "emergency", "fireman"], category: "Travel" },
  { emoji: "🚐", name: "minibus", keywords: ["van", "minibus", "transport"], category: "Travel" },
  { emoji: "🛻", name: "pickup truck", keywords: ["truck", "pickup", "vehicle"], category: "Travel" },
  { emoji: "🚚", name: "delivery truck", keywords: ["truck", "delivery", "shipping"], category: "Travel" },
  { emoji: "🚛", name: "articulated lorry", keywords: ["truck", "semi", "freight"], category: "Travel" },
  { emoji: "🚜", name: "tractor", keywords: ["tractor", "farm", "agriculture"], category: "Travel" },
  { emoji: "🏍️", name: "motorcycle", keywords: ["motorcycle", "motorbike", "ride"], category: "Travel" },
  { emoji: "🛵", name: "motor scooter", keywords: ["scooter", "moped", "ride"], category: "Travel" },
  { emoji: "🚲", name: "bicycle", keywords: ["bike", "bicycle", "cycle", "eco"], category: "Travel" },
  { emoji: "🛴", name: "kick scooter", keywords: ["scooter", "ride", "wheels"], category: "Travel" },
  { emoji: "🛹", name: "skateboard", keywords: ["skateboard", "skate", "sport"], category: "Travel" },
  { emoji: "🛼", name: "roller skate", keywords: ["roller skate", "skating", "wheels"], category: "Travel" },
  { emoji: "🚁", name: "helicopter", keywords: ["helicopter", "fly", "rotor"], category: "Travel" },
  { emoji: "✈️", name: "airplane", keywords: ["airplane", "plane", "fly", "travel"], category: "Travel" },
  { emoji: "🛩️", name: "small airplane", keywords: ["airplane", "plane", "private"], category: "Travel" },
  { emoji: "🚀", name: "rocket", keywords: ["rocket", "space", "launch", "nasa"], category: "Travel" },
  { emoji: "🛸", name: "flying saucer", keywords: ["ufo", "alien", "space"], category: "Travel" },
  { emoji: "🚢", name: "ship", keywords: ["ship", "cruise", "ocean", "boat"], category: "Travel" },
  { emoji: "⛵", name: "sailboat", keywords: ["sailboat", "sailing", "ocean"], category: "Travel" },
  { emoji: "🚤", name: "speedboat", keywords: ["speedboat", "fast", "water"], category: "Travel" },
  { emoji: "⛽", name: "fuel pump", keywords: ["gas", "fuel", "petrol", "station"], category: "Travel" },
  { emoji: "🗺️", name: "world map", keywords: ["map", "world", "travel", "geography"], category: "Travel" },
  { emoji: "🧭", name: "compass", keywords: ["compass", "navigate", "direction"], category: "Travel" },
  { emoji: "🏔️", name: "snow-capped mountain", keywords: ["mountain", "snow", "peak"], category: "Travel" },
  { emoji: "⛰️", name: "mountain", keywords: ["mountain", "peak", "hike"], category: "Travel" },
  { emoji: "🌋", name: "volcano", keywords: ["volcano", "eruption", "lava"], category: "Travel" },
  { emoji: "🗻", name: "mount fuji", keywords: ["fuji", "japan", "mountain"], category: "Travel" },
  { emoji: "🏕️", name: "camping", keywords: ["camping", "tent", "outdoors"], category: "Travel" },
  { emoji: "🏖️", name: "beach with umbrella", keywords: ["beach", "summer", "vacation", "sea"], category: "Travel" },
  { emoji: "🏜️", name: "desert", keywords: ["desert", "sand", "hot", "dry"], category: "Travel" },
  { emoji: "🏝️", name: "desert island", keywords: ["island", "tropical", "palm"], category: "Travel" },
  { emoji: "🏟️", name: "stadium", keywords: ["stadium", "sports", "arena"], category: "Travel" },
  { emoji: "🏛️", name: "classical building", keywords: ["museum", "government", "classic"], category: "Travel" },
  { emoji: "🏗️", name: "building construction", keywords: ["construction", "building", "crane"], category: "Travel" },
  { emoji: "🧱", name: "brick", keywords: ["brick", "wall", "construction"], category: "Travel" },
  { emoji: "🏘️", name: "houses", keywords: ["houses", "neighborhood", "suburb"], category: "Travel" },
  { emoji: "🏚️", name: "derelict house", keywords: ["abandoned", "house", "broken"], category: "Travel" },
  { emoji: "🏠", name: "house", keywords: ["house", "home", "building"], category: "Travel" },
  { emoji: "🏡", name: "house with garden", keywords: ["house", "garden", "home"], category: "Travel" },
  { emoji: "🏢", name: "office building", keywords: ["office", "building", "work", "city"], category: "Travel" },
  { emoji: "🏣", name: "japanese post office", keywords: ["post office", "japan", "mail"], category: "Travel" },
  { emoji: "🏥", name: "hospital", keywords: ["hospital", "medical", "health"], category: "Travel" },
  { emoji: "🏦", name: "bank", keywords: ["bank", "money", "finance"], category: "Travel" },
  { emoji: "🏨", name: "hotel", keywords: ["hotel", "travel", "accommodation"], category: "Travel" },
  { emoji: "🌃", name: "night with stars", keywords: ["night", "city", "stars", "evening"], category: "Travel" },
  { emoji: "🌆", name: "cityscape at dusk", keywords: ["city", "dusk", "sunset", "urban"], category: "Travel" },
  { emoji: "🌇", name: "sunset", keywords: ["sunset", "city", "evening"], category: "Travel" },
  { emoji: "🌉", name: "bridge at night", keywords: ["bridge", "night", "city"], category: "Travel" },
  { emoji: "🗼", name: "tokyo tower", keywords: ["tokyo", "tower", "japan"], category: "Travel" },
  { emoji: "🗽", name: "statue of liberty", keywords: ["liberty", "new york", "usa", "freedom"], category: "Travel" },
  { emoji: "⛪", name: "church", keywords: ["church", "religion", "christian"], category: "Travel" },
  { emoji: "🕌", name: "mosque", keywords: ["mosque", "islam", "muslim"], category: "Travel" },
  { emoji: "🛕", name: "hindu temple", keywords: ["temple", "hindu", "religion"], category: "Travel" },
  { emoji: "🕍", name: "synagogue", keywords: ["synagogue", "jewish", "religion"], category: "Travel" },
  { emoji: "⛩️", name: "shinto shrine", keywords: ["shrine", "japan", "shinto"], category: "Travel" },
  { emoji: "⛲", name: "fountain", keywords: ["fountain", "water", "park"], category: "Travel" },
  { emoji: "🎡", name: "ferris wheel", keywords: ["ferris wheel", "amusement", "park"], category: "Travel" },
  { emoji: "🎢", name: "roller coaster", keywords: ["roller coaster", "thrill", "amusement"], category: "Travel" },
  { emoji: "🎠", name: "carousel horse", keywords: ["carousel", "merry-go-round", "amusement"], category: "Travel" },
  { emoji: "🛝", name: "playground slide", keywords: ["slide", "playground", "kids"], category: "Travel" },

  // Activities
  { emoji: "⚽", name: "soccer ball", keywords: ["soccer", "football", "sport", "ball"], category: "Activities" },
  { emoji: "🏀", name: "basketball", keywords: ["basketball", "sport", "nba", "ball"], category: "Activities" },
  { emoji: "🏈", name: "american football", keywords: ["football", "nfl", "american", "sport"], category: "Activities" },
  { emoji: "⚾", name: "baseball", keywords: ["baseball", "sport", "mlb", "ball"], category: "Activities" },
  { emoji: "🥎", name: "softball", keywords: ["softball", "sport", "ball"], category: "Activities" },
  { emoji: "🎾", name: "tennis", keywords: ["tennis", "sport", "ball", "racket"], category: "Activities" },
  { emoji: "🏐", name: "volleyball", keywords: ["volleyball", "sport", "ball"], category: "Activities" },
  { emoji: "🏉", name: "rugby football", keywords: ["rugby", "sport", "ball"], category: "Activities" },
  { emoji: "🥏", name: "flying disc", keywords: ["frisbee", "disc", "sport"], category: "Activities" },
  { emoji: "🎱", name: "pool 8 ball", keywords: ["billiards", "pool", "8 ball"], category: "Activities" },
  { emoji: "🪀", name: "yo-yo", keywords: ["yo-yo", "toy", "play"], category: "Activities" },
  { emoji: "🏓", name: "ping pong", keywords: ["ping pong", "table tennis", "sport"], category: "Activities" },
  { emoji: "🏸", name: "badminton", keywords: ["badminton", "racket", "sport"], category: "Activities" },
  { emoji: "🏒", name: "ice hockey", keywords: ["hockey", "ice", "puck"], category: "Activities" },
  { emoji: "🏑", name: "field hockey", keywords: ["hockey", "field", "sport"], category: "Activities" },
  { emoji: "🏏", name: "cricket game", keywords: ["cricket", "sport", "bat"], category: "Activities" },
  { emoji: "🥅", name: "goal net", keywords: ["goal", "net", "soccer", "hockey"], category: "Activities" },
  { emoji: "⛳", name: "flag in hole", keywords: ["golf", "hole", "sport"], category: "Activities" },
  { emoji: "🪃", name: "boomerang", keywords: ["boomerang", "australia", "throw"], category: "Activities" },
  { emoji: "🏹", name: "bow and arrow", keywords: ["bow", "arrow", "archery"], category: "Activities" },
  { emoji: "🎯", name: "bullseye", keywords: ["target", "bullseye", "goal", "aim"], category: "Activities" },
  { emoji: "🪁", name: "slingshot", keywords: ["slingshot", "catapult", "weapon"], category: "Activities" },
  { emoji: "🎣", name: "fishing pole", keywords: ["fishing", "fish", "hobby"], category: "Activities" },
  { emoji: "🤿", name: "diving mask", keywords: ["diving", "snorkel", "underwater"], category: "Activities" },
  { emoji: "🎽", name: "running shirt", keywords: ["running", "sport", "athletic"], category: "Activities" },
  { emoji: "🎿", name: "skis", keywords: ["ski", "skiing", "winter", "snow"], category: "Activities" },
  { emoji: "🛷", name: "sled", keywords: ["sled", "sledge", "snow", "winter"], category: "Activities" },
  { emoji: "🥌", name: "curling stone", keywords: ["curling", "winter", "sport"], category: "Activities" },
  { emoji: "🎮", name: "video game", keywords: ["game", "controller", "gaming", "play"], category: "Activities" },
  { emoji: "🕹️", name: "joystick", keywords: ["joystick", "game", "arcade"], category: "Activities" },
  { emoji: "🎲", name: "game die", keywords: ["dice", "game", "luck", "random"], category: "Activities" },
  { emoji: "🧩", name: "puzzle piece", keywords: ["puzzle", "piece", "jigsaw", "fit"], category: "Activities" },
  { emoji: "🪄", name: "magic wand", keywords: ["magic", "wand", "wizard", "trick"], category: "Activities" },
  { emoji: "🃏", name: "joker", keywords: ["joker", "card", "playing cards", "wild"], category: "Activities" },
  { emoji: "🀄", name: "mahjong red dragon", keywords: ["mahjong", "chinese", "game"], category: "Activities" },
  { emoji: "🎴", name: "flower playing cards", keywords: ["cards", "japanese", "game"], category: "Activities" },
  { emoji: "🎭", name: "performing arts", keywords: ["theater", "drama", "mask", "arts"], category: "Activities" },
  { emoji: "🖼️", name: "framed picture", keywords: ["art", "painting", "picture", "frame"], category: "Activities" },
  { emoji: "🎨", name: "artist palette", keywords: ["art", "paint", "palette", "creative"], category: "Activities" },
  { emoji: "🧵", name: "thread", keywords: ["thread", "sewing", "needle"], category: "Activities" },
  { emoji: "🪡", name: "spool of thread", keywords: ["thread", "sewing", "craft"], category: "Activities" },
  { emoji: "🧶", name: "yarn", keywords: ["yarn", "knitting", "craft"], category: "Activities" },
  { emoji: "🪢", name: "knot", keywords: ["knot", "rope", "tie"], category: "Activities" },
  { emoji: "🎤", name: "microphone", keywords: ["microphone", "sing", "music", "karaoke"], category: "Activities" },
  { emoji: "🎧", name: "headphone", keywords: ["headphones", "music", "listen", "audio"], category: "Activities" },
  { emoji: "🎼", name: "musical score", keywords: ["music", "score", "notes"], category: "Activities" },
  { emoji: "🎵", name: "musical note", keywords: ["music", "note", "song"], category: "Activities" },
  { emoji: "🎶", name: "musical notes", keywords: ["music", "notes", "song", "melody"], category: "Activities" },
  { emoji: "🎷", name: "saxophone", keywords: ["saxophone", "jazz", "music"], category: "Activities" },
  { emoji: "🪗", name: "accordion", keywords: ["accordion", "music", "folk"], category: "Activities" },
  { emoji: "🎸", name: "guitar", keywords: ["guitar", "music", "rock", "play"], category: "Activities" },
  { emoji: "🎹", name: "musical keyboard", keywords: ["piano", "keyboard", "music"], category: "Activities" },
  { emoji: "🎺", name: "trumpet", keywords: ["trumpet", "jazz", "music"], category: "Activities" },
  { emoji: "🎻", name: "violin", keywords: ["violin", "classical", "music"], category: "Activities" },
  { emoji: "🪘", name: "long drum", keywords: ["drum", "music", "percussion"], category: "Activities" },
  { emoji: "🥁", name: "drum", keywords: ["drum", "percussion", "music", "beat"], category: "Activities" },
  { emoji: "🪩", name: "mirror ball", keywords: ["disco", "dance", "party", "mirror ball"], category: "Activities" },
  { emoji: "🎬", name: "clapper board", keywords: ["movie", "film", "action", "cinema"], category: "Activities" },
  { emoji: "🎤", name: "microphone", keywords: ["mic", "sing", "perform"], category: "Activities" },
  { emoji: "🎪", name: "circus tent", keywords: ["circus", "tent", "fun"], category: "Activities" },
  { emoji: "🏋️", name: "person lifting weights", keywords: ["weightlifting", "gym", "strong", "workout"], category: "Activities" },
  { emoji: "🤸", name: "person cartwheeling", keywords: ["gymnastics", "cartwheel", "flexible"], category: "Activities" },
  { emoji: "🤼", name: "people wrestling", keywords: ["wrestling", "fight", "sport"], category: "Activities" },
  { emoji: "🤺", name: "person fencing", keywords: ["fencing", "sword", "sport"], category: "Activities" },
  { emoji: "🏇", name: "horse racing", keywords: ["horse racing", "jockey", "sport"], category: "Activities" },
  { emoji: "⛷️", name: "skier", keywords: ["skiing", "ski", "winter", "snow"], category: "Activities" },
  { emoji: "🏄", name: "person surfing", keywords: ["surfing", "surf", "wave", "beach"], category: "Activities" },
  { emoji: "🏊", name: "person swimming", keywords: ["swimming", "swim", "water", "sport"], category: "Activities" },
  { emoji: "🤽", name: "person playing water polo", keywords: ["water polo", "swimming", "sport"], category: "Activities" },
  { emoji: "🚣", name: "person rowing boat", keywords: ["rowing", "boat", "water", "sport"], category: "Activities" },
  { emoji: "🧗", name: "person climbing", keywords: ["climbing", "rock climbing", "sport"], category: "Activities" },
  { emoji: "🚵", name: "person mountain biking", keywords: ["mountain bike", "cycling", "sport"], category: "Activities" },
  { emoji: "🚴", name: "person biking", keywords: ["cycling", "bike", "sport"], category: "Activities" },
  { emoji: "🏆", name: "trophy", keywords: ["trophy", "win", "award", "champion"], category: "Activities" },
  { emoji: "🥇", name: "1st place medal", keywords: ["gold", "first", "medal", "win"], category: "Activities" },
  { emoji: "🥈", name: "2nd place medal", keywords: ["silver", "second", "medal"], category: "Activities" },
  { emoji: "🥉", name: "3rd place medal", keywords: ["bronze", "third", "medal"], category: "Activities" },
  { emoji: "🏅", name: "sports medal", keywords: ["medal", "award", "sport"], category: "Activities" },
  { emoji: "🎖️", name: "military medal", keywords: ["medal", "military", "honor"], category: "Activities" },
  { emoji: "🎗️", name: "reminder ribbon", keywords: ["ribbon", "awareness", "remember"], category: "Activities" },
  { emoji: "🎫", name: "ticket", keywords: ["ticket", "event", "concert"], category: "Activities" },
  { emoji: "🎟️", name: "admission tickets", keywords: ["tickets", "admission", "event"], category: "Activities" },
  { emoji: "🎪", name: "circus tent", keywords: ["circus", "tent", "show"], category: "Activities" },

  // Objects
  { emoji: "👓", name: "glasses", keywords: ["glasses", "eyewear", "sight"], category: "Objects" },
  { emoji: "🕶️", name: "sunglasses", keywords: ["sunglasses", "cool", "shades"], category: "Objects" },
  { emoji: "🥽", name: "goggles", keywords: ["goggles", "protect", "safety"], category: "Objects" },
  { emoji: "🥼", name: "lab coat", keywords: ["lab coat", "doctor", "scientist"], category: "Objects" },
  { emoji: "🦺", name: "safety vest", keywords: ["vest", "safety", "worker"], category: "Objects" },
  { emoji: "👔", name: "necktie", keywords: ["tie", "necktie", "formal", "business"], category: "Objects" },
  { emoji: "👕", name: "t-shirt", keywords: ["t-shirt", "shirt", "clothing"], category: "Objects" },
  { emoji: "👖", name: "jeans", keywords: ["jeans", "pants", "denim"], category: "Objects" },
  { emoji: "🧣", name: "scarf", keywords: ["scarf", "winter", "warm"], category: "Objects" },
  { emoji: "🧤", name: "gloves", keywords: ["gloves", "winter", "warm"], category: "Objects" },
  { emoji: "🧥", name: "coat", keywords: ["coat", "jacket", "winter"], category: "Objects" },
  { emoji: "🧦", name: "socks", keywords: ["socks", "feet", "clothing"], category: "Objects" },
  { emoji: "👗", name: "dress", keywords: ["dress", "clothing", "fashion"], category: "Objects" },
  { emoji: "👘", name: "kimono", keywords: ["kimono", "japanese", "dress"], category: "Objects" },
  { emoji: "🥻", name: "sari", keywords: ["sari", "indian", "dress"], category: "Objects" },
  { emoji: "🩱", name: "one-piece swimsuit", keywords: ["swimsuit", "beach", "swimming"], category: "Objects" },
  { emoji: "🩲", name: "briefs", keywords: ["underwear", "briefs", "clothing"], category: "Objects" },
  { emoji: "🩳", name: "shorts", keywords: ["shorts", "summer", "clothing"], category: "Objects" },
  { emoji: "👙", name: "bikini", keywords: ["bikini", "beach", "swim"], category: "Objects" },
  { emoji: "👚", name: "woman's clothes", keywords: ["blouse", "clothing", "fashion"], category: "Objects" },
  { emoji: "👛", name: "purse", keywords: ["purse", "money", "bag"], category: "Objects" },
  { emoji: "👜", name: "handbag", keywords: ["handbag", "bag", "fashion"], category: "Objects" },
  { emoji: "👝", name: "clutch bag", keywords: ["bag", "clutch", "fashion"], category: "Objects" },
  { emoji: "🛍️", name: "shopping bags", keywords: ["shopping", "bag", "buy"], category: "Objects" },
  { emoji: "🎒", name: "backpack", keywords: ["backpack", "bag", "school", "travel"], category: "Objects" },
  { emoji: "🧳", name: "luggage", keywords: ["luggage", "travel", "suitcase"], category: "Objects" },
  { emoji: "👒", name: "woman's hat", keywords: ["hat", "summer", "fashion"], category: "Objects" },
  { emoji: "🎩", name: "top hat", keywords: ["hat", "formal", "magic"], category: "Objects" },
  { emoji: "🧢", name: "billed cap", keywords: ["cap", "hat", "baseball cap"], category: "Objects" },
  { emoji: "⛑️", name: "rescue worker's helmet", keywords: ["helmet", "safety", "rescue"], category: "Objects" },
  { emoji: "👑", name: "crown", keywords: ["crown", "king", "queen", "royal"], category: "Objects" },
  { emoji: "💍", name: "ring", keywords: ["ring", "wedding", "engagement", "jewelry"], category: "Objects" },
  { emoji: "💎", name: "gem stone", keywords: ["diamond", "gem", "jewelry", "wealth"], category: "Objects" },
  { emoji: "📱", name: "mobile phone", keywords: ["phone", "mobile", "smartphone", "iphone"], category: "Objects" },
  { emoji: "💻", name: "laptop", keywords: ["laptop", "computer", "work", "tech"], category: "Objects" },
  { emoji: "⌨️", name: "keyboard", keywords: ["keyboard", "type", "computer"], category: "Objects" },
  { emoji: "🖥️", name: "desktop computer", keywords: ["computer", "monitor", "desktop"], category: "Objects" },
  { emoji: "🖨️", name: "printer", keywords: ["printer", "print", "office"], category: "Objects" },
  { emoji: "🖱️", name: "computer mouse", keywords: ["mouse", "click", "computer"], category: "Objects" },
  { emoji: "💾", name: "floppy disk", keywords: ["floppy", "save", "disk", "retro"], category: "Objects" },
  { emoji: "💿", name: "optical disk", keywords: ["cd", "dvd", "disk", "music"], category: "Objects" },
  { emoji: "📀", name: "dvd", keywords: ["dvd", "disk", "movie"], category: "Objects" },
  { emoji: "📷", name: "camera", keywords: ["camera", "photo", "picture"], category: "Objects" },
  { emoji: "📸", name: "camera with flash", keywords: ["camera", "flash", "photo"], category: "Objects" },
  { emoji: "📹", name: "video camera", keywords: ["video", "camera", "record"], category: "Objects" },
  { emoji: "📺", name: "television", keywords: ["tv", "television", "watch"], category: "Objects" },
  { emoji: "📻", name: "radio", keywords: ["radio", "music", "broadcast"], category: "Objects" },
  { emoji: "📞", name: "telephone receiver", keywords: ["phone", "call", "telephone"], category: "Objects" },
  { emoji: "☎️", name: "telephone", keywords: ["phone", "retro", "call"], category: "Objects" },
  { emoji: "🔋", name: "battery", keywords: ["battery", "power", "energy"], category: "Objects" },
  { emoji: "🪫", name: "low battery", keywords: ["battery", "low", "dead"], category: "Objects" },
  { emoji: "🔌", name: "electric plug", keywords: ["plug", "power", "electric"], category: "Objects" },
  { emoji: "💡", name: "light bulb", keywords: ["bulb", "idea", "light", "bright"], category: "Objects" },
  { emoji: "🔦", name: "flashlight", keywords: ["flashlight", "torch", "light"], category: "Objects" },
  { emoji: "🕯️", name: "candle", keywords: ["candle", "light", "romantic"], category: "Objects" },
  { emoji: "🪔", name: "diya lamp", keywords: ["diya", "lamp", "indian", "diwali"], category: "Objects" },
  { emoji: "🧯", name: "fire extinguisher", keywords: ["fire", "extinguisher", "safety"], category: "Objects" },
  { emoji: "🛢️", name: "oil drum", keywords: ["oil", "drum", "barrel"], category: "Objects" },
  { emoji: "💸", name: "money with wings", keywords: ["money", "fly", "spend", "cash"], category: "Objects" },
  { emoji: "💵", name: "dollar banknote", keywords: ["dollar", "money", "cash", "usd"], category: "Objects" },
  { emoji: "💴", name: "yen banknote", keywords: ["yen", "money", "japan"], category: "Objects" },
  { emoji: "💰", name: "money bag", keywords: ["money", "bag", "rich", "wealth"], category: "Objects" },
  { emoji: "💳", name: "credit card", keywords: ["credit card", "payment", "money"], category: "Objects" },
  { emoji: "🪙", name: "coin", keywords: ["coin", "money", "gold"], category: "Objects" },
  { emoji: "💹", name: "chart increasing with yen", keywords: ["chart", "money", "stock", "increase"], category: "Objects" },
  { emoji: "📈", name: "chart increasing", keywords: ["chart", "up", "growth", "stock"], category: "Objects" },
  { emoji: "📉", name: "chart decreasing", keywords: ["chart", "down", "decline", "stock"], category: "Objects" },
  { emoji: "📊", name: "bar chart", keywords: ["chart", "data", "graph", "analytics"], category: "Objects" },
  { emoji: "📋", name: "clipboard", keywords: ["clipboard", "list", "checklist"], category: "Objects" },
  { emoji: "📌", name: "pushpin", keywords: ["pin", "location", "mark"], category: "Objects" },
  { emoji: "📍", name: "round pushpin", keywords: ["pin", "location", "map"], category: "Objects" },
  { emoji: "📎", name: "paperclip", keywords: ["paperclip", "attach", "link"], category: "Objects" },
  { emoji: "🖇️", name: "linked paperclips", keywords: ["paperclip", "link", "attach"], category: "Objects" },
  { emoji: "📏", name: "straight ruler", keywords: ["ruler", "measure", "straight"], category: "Objects" },
  { emoji: "📐", name: "triangular ruler", keywords: ["ruler", "triangle", "measure"], category: "Objects" },
  { emoji: "✂️", name: "scissors", keywords: ["scissors", "cut", "craft"], category: "Objects" },
  { emoji: "🗃️", name: "card file box", keywords: ["file", "organize", "cards"], category: "Objects" },
  { emoji: "🗄️", name: "file cabinet", keywords: ["cabinet", "file", "organize"], category: "Objects" },
  { emoji: "🗑️", name: "wastebasket", keywords: ["trash", "delete", "garbage", "bin"], category: "Objects" },
  { emoji: "🔒", name: "locked", keywords: ["locked", "secure", "password", "private"], category: "Objects" },
  { emoji: "🔓", name: "unlocked", keywords: ["unlocked", "open", "access"], category: "Objects" },
  { emoji: "🔐", name: "locked with key", keywords: ["locked", "key", "secure"], category: "Objects" },
  { emoji: "🔑", name: "key", keywords: ["key", "lock", "access", "password"], category: "Objects" },
  { emoji: "🗝️", name: "old key", keywords: ["key", "old", "vintage", "lock"], category: "Objects" },
  { emoji: "🔨", name: "hammer", keywords: ["hammer", "tool", "build"], category: "Objects" },
  { emoji: "🪓", name: "axe", keywords: ["axe", "chop", "wood"], category: "Objects" },
  { emoji: "⛏️", name: "pick", keywords: ["pick", "mine", "dig"], category: "Objects" },
  { emoji: "🔧", name: "wrench", keywords: ["wrench", "tool", "fix", "repair"], category: "Objects" },
  { emoji: "🪛", name: "screwdriver", keywords: ["screwdriver", "tool", "fix"], category: "Objects" },
  { emoji: "🔩", name: "nut and bolt", keywords: ["bolt", "nut", "screw", "tool"], category: "Objects" },
  { emoji: "🪝", name: "hook", keywords: ["hook", "hang", "fishing"], category: "Objects" },
  { emoji: "🧲", name: "magnet", keywords: ["magnet", "attract", "metal"], category: "Objects" },
  { emoji: "🔬", name: "microscope", keywords: ["microscope", "science", "lab"], category: "Objects" },
  { emoji: "🔭", name: "telescope", keywords: ["telescope", "space", "astronomy"], category: "Objects" },
  { emoji: "🩺", name: "stethoscope", keywords: ["stethoscope", "doctor", "medical"], category: "Objects" },
  { emoji: "💊", name: "pill", keywords: ["pill", "medicine", "drug", "health"], category: "Objects" },
  { emoji: "🩹", name: "adhesive bandage", keywords: ["bandage", "band-aid", "wound"], category: "Objects" },
  { emoji: "🩻", name: "x-ray", keywords: ["x-ray", "medical", "bone"], category: "Objects" },
  { emoji: "🚪", name: "door", keywords: ["door", "enter", "exit", "open"], category: "Objects" },
  { emoji: "🪞", name: "mirror", keywords: ["mirror", "reflect", "beauty"], category: "Objects" },
  { emoji: "🪟", name: "window", keywords: ["window", "glass", "view"], category: "Objects" },
  { emoji: "🛋️", name: "couch and lamp", keywords: ["couch", "sofa", "furniture", "relax"], category: "Objects" },
  { emoji: "🪑", name: "chair", keywords: ["chair", "seat", "furniture"], category: "Objects" },
  { emoji: "🚽", name: "toilet", keywords: ["toilet", "bathroom", "flush"], category: "Objects" },
  { emoji: "🪠", name: "plunger", keywords: ["plunger", "toilet", "unclog"], category: "Objects" },
  { emoji: "🚿", name: "shower", keywords: ["shower", "bath", "clean"], category: "Objects" },
  { emoji: "🛁", name: "bathtub", keywords: ["bath", "tub", "relax", "clean"], category: "Objects" },
  { emoji: "📦", name: "package", keywords: ["package", "box", "delivery", "shipping"], category: "Objects" },
  { emoji: "📫", name: "closed mailbox with raised flag", keywords: ["mailbox", "mail", "letter"], category: "Objects" },
  { emoji: "📬", name: "open mailbox with raised flag", keywords: ["mailbox", "mail", "open"], category: "Objects" },
  { emoji: "📭", name: "open mailbox with lowered flag", keywords: ["mailbox", "empty", "mail"], category: "Objects" },
  { emoji: "📮", name: "postbox", keywords: ["postbox", "mail", "letter"], category: "Objects" },
  { emoji: "📝", name: "memo", keywords: ["memo", "note", "write", "document"], category: "Objects" },
  { emoji: "✏️", name: "pencil", keywords: ["pencil", "write", "draw"], category: "Objects" },
  { emoji: "🖊️", name: "pen", keywords: ["pen", "write", "sign"], category: "Objects" },
  { emoji: "🖋️", name: "fountain pen", keywords: ["pen", "write", "fancy"], category: "Objects" },
  { emoji: "🖌️", name: "paintbrush", keywords: ["brush", "paint", "art"], category: "Objects" },
  { emoji: "📖", name: "open book", keywords: ["book", "read", "study", "education"], category: "Objects" },
  { emoji: "📚", name: "books", keywords: ["books", "library", "read", "education"], category: "Objects" },
  { emoji: "📰", name: "newspaper", keywords: ["newspaper", "news", "read", "press"], category: "Objects" },
  { emoji: "🗞️", name: "rolled-up newspaper", keywords: ["newspaper", "press", "rolled"], category: "Objects" },
  { emoji: "📄", name: "page facing up", keywords: ["document", "page", "file"], category: "Objects" },
  { emoji: "📃", name: "page with curl", keywords: ["document", "page", "curl"], category: "Objects" },
  { emoji: "📜", name: "scroll", keywords: ["scroll", "ancient", "document"], category: "Objects" },
  { emoji: "📑", name: "bookmark tabs", keywords: ["bookmark", "tabs", "document"], category: "Objects" },
  { emoji: "🔖", name: "bookmark", keywords: ["bookmark", "save", "mark"], category: "Objects" },
  { emoji: "🏷️", name: "label", keywords: ["label", "tag", "price"], category: "Objects" },
  { emoji: "💰", name: "money bag", keywords: ["money", "bag", "wealth"], category: "Objects" },
  { emoji: "🎁", name: "wrapped gift", keywords: ["gift", "present", "birthday", "christmas"], category: "Objects" },
  { emoji: "🎀", name: "ribbon", keywords: ["ribbon", "gift", "bow", "pretty"], category: "Objects" },
  { emoji: "🎊", name: "confetti ball", keywords: ["confetti", "celebrate", "party"], category: "Objects" },
  { emoji: "🎉", name: "party popper", keywords: ["party", "celebrate", "confetti", "tada"], category: "Objects" },
  { emoji: "🎈", name: "balloon", keywords: ["balloon", "party", "birthday", "celebrate"], category: "Objects" },
  { emoji: "🎏", name: "carp streamer", keywords: ["streamer", "japanese", "celebrate"], category: "Objects" },
  { emoji: "✨", name: "sparkles", keywords: ["sparkle", "star", "glitter", "magic"], category: "Objects" },
  { emoji: "🎇", name: "sparkler", keywords: ["sparkler", "fireworks", "light"], category: "Objects" },
  { emoji: "🎆", name: "fireworks", keywords: ["fireworks", "celebrate", "new year"], category: "Objects" },
  { emoji: "🕰️", name: "mantelpiece clock", keywords: ["clock", "time", "watch"], category: "Objects" },
  { emoji: "⌚", name: "watch", keywords: ["watch", "time", "wrist"], category: "Objects" },
  { emoji: "⏰", name: "alarm clock", keywords: ["alarm", "wake up", "morning", "clock"], category: "Objects" },
  { emoji: "⌛", name: "hourglass done", keywords: ["hourglass", "time", "sand"], category: "Objects" },
  { emoji: "⏳", name: "hourglass not done", keywords: ["hourglass", "wait", "time"], category: "Objects" },
  { emoji: "📡", name: "satellite antenna", keywords: ["satellite", "antenna", "signal", "space"], category: "Objects" },
  { emoji: "🔊", name: "speaker high volume", keywords: ["speaker", "loud", "volume", "sound"], category: "Objects" },
  { emoji: "🔇", name: "muted speaker", keywords: ["mute", "silent", "speaker"], category: "Objects" },
  { emoji: "📣", name: "megaphone", keywords: ["megaphone", "loud", "announce"], category: "Objects" },
  { emoji: "🔔", name: "bell", keywords: ["bell", "ring", "notification", "alert"], category: "Objects" },
  { emoji: "🔕", name: "bell with slash", keywords: ["bell", "mute", "silent", "no ring"], category: "Objects" },

  // Symbols
  { emoji: "❤️", name: "red heart", keywords: ["heart", "love", "red", "romance"], category: "Symbols" },
  { emoji: "🧡", name: "orange heart", keywords: ["heart", "orange", "love"], category: "Symbols" },
  { emoji: "💛", name: "yellow heart", keywords: ["heart", "yellow", "love", "happy"], category: "Symbols" },
  { emoji: "💚", name: "green heart", keywords: ["heart", "green", "love", "nature"], category: "Symbols" },
  { emoji: "💙", name: "blue heart", keywords: ["heart", "blue", "love", "calm"], category: "Symbols" },
  { emoji: "💜", name: "purple heart", keywords: ["heart", "purple", "love"], category: "Symbols" },
  { emoji: "🖤", name: "black heart", keywords: ["heart", "black", "dark", "goth"], category: "Symbols" },
  { emoji: "🤍", name: "white heart", keywords: ["heart", "white", "pure", "love"], category: "Symbols" },
  { emoji: "🤎", name: "brown heart", keywords: ["heart", "brown", "love"], category: "Symbols" },
  { emoji: "💔", name: "broken heart", keywords: ["heart", "broken", "sad", "breakup"], category: "Symbols" },
  { emoji: "❤️‍🔥", name: "heart on fire", keywords: ["heart", "fire", "passion", "love"], category: "Symbols" },
  { emoji: "❤️‍🩹", name: "mending heart", keywords: ["heart", "healing", "love", "repair"], category: "Symbols" },
  { emoji: "💕", name: "two hearts", keywords: ["hearts", "love", "couple"], category: "Symbols" },
  { emoji: "💞", name: "revolving hearts", keywords: ["hearts", "love", "spin"], category: "Symbols" },
  { emoji: "💓", name: "beating heart", keywords: ["heart", "beat", "pulse", "love"], category: "Symbols" },
  { emoji: "💗", name: "growing heart", keywords: ["heart", "grow", "love", "pink"], category: "Symbols" },
  { emoji: "💖", name: "sparkling heart", keywords: ["heart", "sparkle", "love"], category: "Symbols" },
  { emoji: "💘", name: "heart with arrow", keywords: ["heart", "arrow", "cupid", "love"], category: "Symbols" },
  { emoji: "💝", name: "heart with ribbon", keywords: ["heart", "ribbon", "gift", "love"], category: "Symbols" },
  { emoji: "💟", name: "heart decoration", keywords: ["heart", "decoration", "love"], category: "Symbols" },
  { emoji: "☮️", name: "peace symbol", keywords: ["peace", "symbol", "hippie"], category: "Symbols" },
  { emoji: "✝️", name: "latin cross", keywords: ["cross", "christian", "church"], category: "Symbols" },
  { emoji: "☪️", name: "star and crescent", keywords: ["islam", "muslim", "moon", "star"], category: "Symbols" },
  { emoji: "🕉️", name: "om", keywords: ["om", "hindu", "meditation", "yoga"], category: "Symbols" },
  { emoji: "✡️", name: "star of david", keywords: ["jewish", "star of david", "judaism"], category: "Symbols" },
  { emoji: "☯️", name: "yin yang", keywords: ["yin yang", "balance", "chinese", "tao"], category: "Symbols" },
  { emoji: "⭐", name: "star", keywords: ["star", "gold", "rating", "yellow"], category: "Symbols" },
  { emoji: "🌟", name: "glowing star", keywords: ["star", "shine", "glow", "special"], category: "Symbols" },
  { emoji: "💫", name: "dizzy", keywords: ["dizzy", "star", "spin"], category: "Symbols" },
  { emoji: "✨", name: "sparkles", keywords: ["sparkle", "clean", "magic", "glitter"], category: "Symbols" },
  { emoji: "🌈", name: "rainbow", keywords: ["rainbow", "colorful", "lgbt", "pride", "weather"], category: "Symbols" },
  { emoji: "☀️", name: "sun", keywords: ["sun", "sunny", "hot", "weather"], category: "Symbols" },
  { emoji: "🌤️", name: "sun behind small cloud", keywords: ["sunny", "cloud", "weather"], category: "Symbols" },
  { emoji: "⛅", name: "sun behind cloud", keywords: ["partly cloudy", "weather", "cloud"], category: "Symbols" },
  { emoji: "🌥️", name: "sun behind large cloud", keywords: ["cloudy", "weather", "cloud"], category: "Symbols" },
  { emoji: "☁️", name: "cloud", keywords: ["cloud", "weather", "sky"], category: "Symbols" },
  { emoji: "🌦️", name: "sun behind rain cloud", keywords: ["rain", "sun", "weather"], category: "Symbols" },
  { emoji: "🌧️", name: "cloud with rain", keywords: ["rain", "weather", "cloudy"], category: "Symbols" },
  { emoji: "⛈️", name: "cloud with lightning and rain", keywords: ["storm", "thunder", "rain"], category: "Symbols" },
  { emoji: "🌩️", name: "cloud with lightning", keywords: ["lightning", "thunder", "storm"], category: "Symbols" },
  { emoji: "🌨️", name: "cloud with snow", keywords: ["snow", "winter", "cold"], category: "Symbols" },
  { emoji: "❄️", name: "snowflake", keywords: ["snow", "cold", "winter", "ice"], category: "Symbols" },
  { emoji: "☃️", name: "snowman", keywords: ["snowman", "winter", "cold", "christmas"], category: "Symbols" },
  { emoji: "⛄", name: "snowman without snow", keywords: ["snowman", "winter", "cold"], category: "Symbols" },
  { emoji: "🌬️", name: "wind face", keywords: ["wind", "blow", "breeze"], category: "Symbols" },
  { emoji: "💨", name: "dashing away", keywords: ["wind", "fast", "dash", "smoke"], category: "Symbols" },
  { emoji: "🌀", name: "cyclone", keywords: ["cyclone", "spiral", "typhoon", "hurricane"], category: "Symbols" },
  { emoji: "🌪️", name: "tornado", keywords: ["tornado", "storm", "wind"], category: "Symbols" },
  { emoji: "🌊", name: "water wave", keywords: ["wave", "ocean", "water", "surf"], category: "Symbols" },
  { emoji: "🔥", name: "fire", keywords: ["fire", "hot", "flame", "burn"], category: "Symbols" },
  { emoji: "💧", name: "droplet", keywords: ["water", "drop", "rain", "blue"], category: "Symbols" },
  { emoji: "🌙", name: "crescent moon", keywords: ["moon", "night", "crescent", "sleep"], category: "Symbols" },
  { emoji: "🌛", name: "first quarter moon face", keywords: ["moon", "night", "crescent"], category: "Symbols" },
  { emoji: "🌝", name: "full moon face", keywords: ["moon", "full moon", "face"], category: "Symbols" },
  { emoji: "🌞", name: "sun with face", keywords: ["sun", "happy", "warm", "summer"], category: "Symbols" },
  { emoji: "⚡", name: "high voltage", keywords: ["lightning", "electric", "power", "fast"], category: "Symbols" },
  { emoji: "🔴", name: "red circle", keywords: ["red", "circle", "dot", "stop"], category: "Symbols" },
  { emoji: "🟠", name: "orange circle", keywords: ["orange", "circle", "dot"], category: "Symbols" },
  { emoji: "🟡", name: "yellow circle", keywords: ["yellow", "circle", "dot"], category: "Symbols" },
  { emoji: "🟢", name: "green circle", keywords: ["green", "circle", "dot", "go"], category: "Symbols" },
  { emoji: "🔵", name: "blue circle", keywords: ["blue", "circle", "dot"], category: "Symbols" },
  { emoji: "🟣", name: "purple circle", keywords: ["purple", "circle", "dot"], category: "Symbols" },
  { emoji: "⚫", name: "black circle", keywords: ["black", "circle", "dot"], category: "Symbols" },
  { emoji: "⚪", name: "white circle", keywords: ["white", "circle", "dot"], category: "Symbols" },
  { emoji: "🟤", name: "brown circle", keywords: ["brown", "circle", "dot"], category: "Symbols" },
  { emoji: "🔶", name: "large orange diamond", keywords: ["orange", "diamond", "shape"], category: "Symbols" },
  { emoji: "🔷", name: "large blue diamond", keywords: ["blue", "diamond", "shape"], category: "Symbols" },
  { emoji: "🔸", name: "small orange diamond", keywords: ["orange", "diamond", "small"], category: "Symbols" },
  { emoji: "🔹", name: "small blue diamond", keywords: ["blue", "diamond", "small"], category: "Symbols" },
  { emoji: "🔺", name: "red triangle pointed up", keywords: ["triangle", "red", "up"], category: "Symbols" },
  { emoji: "🔻", name: "red triangle pointed down", keywords: ["triangle", "red", "down"], category: "Symbols" },
  { emoji: "💠", name: "diamond with a dot", keywords: ["diamond", "blue", "dot"], category: "Symbols" },
  { emoji: "🔘", name: "radio button", keywords: ["radio button", "circle", "select"], category: "Symbols" },
  { emoji: "✅", name: "check mark button", keywords: ["check", "done", "yes", "correct"], category: "Symbols" },
  { emoji: "❌", name: "cross mark", keywords: ["x", "no", "wrong", "error", "cancel"], category: "Symbols" },
  { emoji: "❎", name: "cross mark button", keywords: ["x", "no", "cancel"], category: "Symbols" },
  { emoji: "⭕", name: "hollow red circle", keywords: ["circle", "red", "o", "correct"], category: "Symbols" },
  { emoji: "🛑", name: "stop sign", keywords: ["stop", "red", "sign", "halt"], category: "Symbols" },
  { emoji: "⛔", name: "no entry", keywords: ["no entry", "stop", "forbidden"], category: "Symbols" },
  { emoji: "🚫", name: "prohibited", keywords: ["no", "banned", "forbidden", "circle"], category: "Symbols" },
  { emoji: "💯", name: "hundred points", keywords: ["100", "hundred", "perfect", "score"], category: "Symbols" },
  { emoji: "💢", name: "anger symbol", keywords: ["angry", "anger", "mad"], category: "Symbols" },
  { emoji: "♻️", name: "recycling symbol", keywords: ["recycle", "environment", "green", "eco"], category: "Symbols" },
  { emoji: "✔️", name: "check mark", keywords: ["check", "done", "correct", "yes"], category: "Symbols" },
  { emoji: "🔃", name: "clockwise vertical arrows", keywords: ["refresh", "reload", "sync"], category: "Symbols" },
  { emoji: "🔄", name: "counterclockwise arrows button", keywords: ["refresh", "reload", "repeat"], category: "Symbols" },
  { emoji: "🔙", name: "back arrow", keywords: ["back", "arrow", "return"], category: "Symbols" },
  { emoji: "🔛", name: "on arrow", keywords: ["on", "arrow"], category: "Symbols" },
  { emoji: "🔝", name: "top arrow", keywords: ["top", "arrow", "up"], category: "Symbols" },
  { emoji: "🆗", name: "ok button", keywords: ["ok", "button", "agree"], category: "Symbols" },
  { emoji: "🆕", name: "new button", keywords: ["new", "button", "badge"], category: "Symbols" },
  { emoji: "🆓", name: "free button", keywords: ["free", "button", "no cost"], category: "Symbols" },
  { emoji: "🆙", name: "up button", keywords: ["up", "button", "upgrade"], category: "Symbols" },
  { emoji: "🆒", name: "cool button", keywords: ["cool", "button"], category: "Symbols" },
  { emoji: "🔞", name: "no one under eighteen", keywords: ["18", "adult", "mature", "restricted"], category: "Symbols" },
  { emoji: "📵", name: "no mobile phones", keywords: ["no phone", "silent", "forbidden"], category: "Symbols" },
  { emoji: "🔱", name: "trident emblem", keywords: ["trident", "poseidon", "symbol"], category: "Symbols" },
  { emoji: "⚜️", name: "fleur-de-lis", keywords: ["fleur de lis", "france", "symbol"], category: "Symbols" },
  { emoji: "🔰", name: "japanese symbol for beginner", keywords: ["beginner", "japanese", "green"], category: "Symbols" },
  { emoji: "⚠️", name: "warning", keywords: ["warning", "caution", "alert", "danger"], category: "Symbols" },
  { emoji: "☢️", name: "radioactive", keywords: ["radioactive", "nuclear", "danger"], category: "Symbols" },
  { emoji: "☣️", name: "biohazard", keywords: ["biohazard", "danger", "toxic"], category: "Symbols" },
  { emoji: "↗️", name: "up-right arrow", keywords: ["arrow", "direction", "up right"], category: "Symbols" },
  { emoji: "↘️", name: "down-right arrow", keywords: ["arrow", "direction", "down right"], category: "Symbols" },
  { emoji: "↙️", name: "down-left arrow", keywords: ["arrow", "direction", "down left"], category: "Symbols" },
  { emoji: "↖️", name: "up-left arrow", keywords: ["arrow", "direction", "up left"], category: "Symbols" },
  { emoji: "↕️", name: "up-down arrow", keywords: ["arrow", "direction", "up down"], category: "Symbols" },
  { emoji: "↔️", name: "left-right arrow", keywords: ["arrow", "direction", "horizontal"], category: "Symbols" },
  { emoji: "🔀", name: "shuffle tracks button", keywords: ["shuffle", "random", "music"], category: "Symbols" },
  { emoji: "🔁", name: "repeat button", keywords: ["repeat", "loop", "music"], category: "Symbols" },
  { emoji: "🔂", name: "repeat single button", keywords: ["repeat once", "loop", "music"], category: "Symbols" },
  { emoji: "▶️", name: "play button", keywords: ["play", "start", "media"], category: "Symbols" },
  { emoji: "⏸️", name: "pause button", keywords: ["pause", "wait", "media"], category: "Symbols" },
  { emoji: "⏹️", name: "stop button", keywords: ["stop", "end", "media"], category: "Symbols" },
  { emoji: "⏭️", name: "next track button", keywords: ["next", "skip", "media"], category: "Symbols" },
  { emoji: "⏮️", name: "last track button", keywords: ["previous", "back", "media"], category: "Symbols" },
  { emoji: "🔇", name: "muted speaker", keywords: ["mute", "silent", "no sound"], category: "Symbols" },
  { emoji: "📳", name: "vibration mode", keywords: ["vibrate", "phone", "silent"], category: "Symbols" },
  { emoji: "📴", name: "mobile phone off", keywords: ["off", "phone", "no mobile"], category: "Symbols" },
  { emoji: "♀️", name: "female sign", keywords: ["female", "woman", "gender"], category: "Symbols" },
  { emoji: "♂️", name: "male sign", keywords: ["male", "man", "gender"], category: "Symbols" },
  { emoji: "⚧️", name: "transgender symbol", keywords: ["transgender", "trans", "gender"], category: "Symbols" },
  { emoji: "✖️", name: "multiply", keywords: ["multiply", "times", "x", "math"], category: "Symbols" },
  { emoji: "➕", name: "plus", keywords: ["plus", "add", "math", "positive"], category: "Symbols" },
  { emoji: "➖", name: "minus", keywords: ["minus", "subtract", "math", "negative"], category: "Symbols" },
  { emoji: "➗", name: "divide", keywords: ["divide", "division", "math"], category: "Symbols" },
  { emoji: "♾️", name: "infinity", keywords: ["infinity", "forever", "loop"], category: "Symbols" },
  { emoji: "🔣", name: "input symbols", keywords: ["symbols", "input", "keyboard"], category: "Symbols" },
  { emoji: "🎵", name: "musical note", keywords: ["music", "note", "song", "sound"], category: "Symbols" },
  { emoji: "🏁", name: "chequered flag", keywords: ["flag", "race", "finish", "checkered"], category: "Symbols" },
  { emoji: "🚩", name: "triangular flag", keywords: ["flag", "red", "warning", "mark"], category: "Symbols" },
  { emoji: "🎌", name: "crossed flags", keywords: ["flags", "crossed", "japan"], category: "Symbols" },
  { emoji: "🏴", name: "black flag", keywords: ["flag", "black", "pirate"], category: "Symbols" },
  { emoji: "🏳️", name: "white flag", keywords: ["flag", "white", "surrender", "peace"], category: "Symbols" },
  { emoji: "🏳️‍🌈", name: "rainbow flag", keywords: ["rainbow", "pride", "lgbt", "flag"], category: "Symbols" },
  { emoji: "🏳️‍⚧️", name: "transgender flag", keywords: ["trans", "pride", "flag"], category: "Symbols" },
  { emoji: "🏴‍☠️", name: "pirate flag", keywords: ["pirate", "skull", "flag", "jolly roger"], category: "Symbols" },
];
