import GradientGenerator from "./components/GradientGenerator";

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="border-b border-border bg-surface/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-md bg-gradient-to-br from-[#7c5cfc] to-[#ff6b9d]" />
            <span className="font-semibold text-foreground">css-gradient</span>
          </div>
          <a
            href="https://github.com"
            target="_blank"
            rel="noopener noreferrer"
            className="text-sm text-muted hover:text-foreground transition-colors"
          >
            GitHub
          </a>
        </div>
      </header>

      <main className="flex-1 max-w-6xl mx-auto px-4 py-8 w-full">
        <div className="mb-8">
          <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-2">
            CSS Gradient Generator
          </h1>
          <p className="text-muted text-lg">
            Create beautiful linear and radial CSS gradients with a live preview.
            Copy the generated code and use it in your projects.
          </p>
        </div>

        <GradientGenerator />

        <article className="mt-16 max-w-none space-y-6 text-muted">
          <h2 className="text-xl font-semibold text-foreground">
            Understanding CSS Gradients
          </h2>
          <p>
            CSS gradients allow you to display smooth transitions between two or
            more specified colors. They are generated by the browser, which means
            they look sharp at any resolution and scale without additional HTTP
            requests. Gradients are commonly used for backgrounds, overlays,
            buttons, and decorative elements in modern web design.
          </p>

          <h3 className="text-lg font-semibold text-foreground">
            Linear Gradients
          </h3>
          <p>
            A linear gradient transitions colors along a straight line. The
            direction is defined by an angle (e.g., <code className="text-accent font-mono text-sm">180deg</code> for
            top-to-bottom) or keywords like <code className="text-accent font-mono text-sm">to right</code>.
            The basic syntax is:{" "}
            <code className="text-accent font-mono text-sm">
              background: linear-gradient(direction, color1, color2, ...);
            </code>
            . You can add color stops with percentage values to control exactly
            where each color appears. For example,{" "}
            <code className="text-accent font-mono text-sm">
              linear-gradient(90deg, #ff6b6b 0%, #feca57 50%, #48dbfb 100%)
            </code>{" "}
            creates a three-color horizontal gradient.
          </p>

          <h3 className="text-lg font-semibold text-foreground">
            Radial Gradients
          </h3>
          <p>
            Radial gradients radiate from a center point outward. They are
            defined with the{" "}
            <code className="text-accent font-mono text-sm">radial-gradient()</code> function. You
            can control the shape (circle or ellipse) and the position of the
            center. For instance,{" "}
            <code className="text-accent font-mono text-sm">
              radial-gradient(circle at 30% 30%, #ff00cc, #333399)
            </code>{" "}
            creates a circular gradient starting from the upper-left area.
            Radial gradients are popular for spotlight effects, glowing orbs, and
            vignette overlays.
          </p>

          <h3 className="text-lg font-semibold text-foreground">
            Browser Support
          </h3>
          <p>
            CSS gradients are supported in all modern browsers including Chrome,
            Firefox, Safari, Edge, and Opera. Vendor prefixes like{" "}
            <code className="text-accent font-mono text-sm">-webkit-</code> are no longer
            needed for most use cases. The standard syntax works across all
            major browsers released after 2015. For older browser support,
            always provide a solid background-color fallback before the gradient
            declaration.
          </p>

          <h3 className="text-lg font-semibold text-foreground">
            Design Tips for Using Gradients
          </h3>
          <p>
            Start with two colors that are close on the color wheel for subtle,
            elegant gradients. Use contrasting colors sparingly for bold,
            attention-grabbing backgrounds. Consider the text readability on top
            of gradient backgrounds by testing with both light and dark text.
            Gradients work well for hero sections, card backgrounds, and call-to-action
            buttons. Combining a gradient with a semi-transparent overlay can
            make text more legible while keeping the visual appeal. Use this
            generator to experiment with different angles, color stops, and
            gradient types until you find the right combination for your design.
          </p>

          <h3 className="text-lg font-semibold text-foreground">
            Tailwind CSS and Gradients
          </h3>
          <p>
            Tailwind CSS provides utility classes for linear gradients using{" "}
            <code className="text-accent font-mono text-sm">bg-gradient-to-r</code>,{" "}
            <code className="text-accent font-mono text-sm">from-[color]</code>,{" "}
            <code className="text-accent font-mono text-sm">via-[color]</code>, and{" "}
            <code className="text-accent font-mono text-sm">to-[color]</code> classes.
            For standard angles (0, 45, 90, etc.) and up to three color stops,
            this generator outputs the equivalent Tailwind classes. For custom
            angles or radial gradients, you can use Tailwind&apos;s arbitrary value
            syntax or inline styles with the CSS output from this tool.
          </p>
        </article>
      </main>

      <footer className="border-t border-gray-200 py-8 text-center">
        <div className="max-w-3xl mx-auto px-4">
          <p className="text-sm text-gray-500 mb-4">
            CSS Gradient Generator — Free online tool. No signup required.
          </p>
          <div className="mb-4">
            <p className="text-xs text-gray-400 mb-2">Related Tools</p>
            <div className="flex flex-wrap justify-center gap-2">
              <a href="https://css-box-shadow-gamma.vercel.app" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 hover:text-blue-800 px-2 py-1 bg-blue-50 rounded">CSS Box Shadow</a>
              <a href="https://color-palette-sand.vercel.app" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 hover:text-blue-800 px-2 py-1 bg-blue-50 rounded">Color Palette</a>
              <a href="https://color-converter-inky.vercel.app" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 hover:text-blue-800 px-2 py-1 bg-blue-50 rounded">Color Converter</a>
              <a href="https://border-radius-nine.vercel.app" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 hover:text-blue-800 px-2 py-1 bg-blue-50 rounded">Border Radius</a>
              <a href="https://css-animation-tawny.vercel.app" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 hover:text-blue-800 px-2 py-1 bg-blue-50 rounded">CSS Animation</a>
            </div>
          </div>
          <div className="flex justify-center gap-3 text-xs text-gray-400">
            <a href="https://cc-tools.vercel.app" target="_blank" rel="noopener noreferrer" className="hover:text-gray-600">53+ Free Tools →</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
