/**
 * Maps the `category` field in tools-config.ts to public category routes.
 * Keep this keyed by category name, not by tool slug, so new tools inherit a
 * category automatically when they are deployed from stock.
 */
export const categorySlugByName: Record<string, string> = {
  "AI": "ai-tools",
  "AI Tools": "ai-tools",
  "AI Workflow": "ai-tools",
  "AI・データベース": "ai-tools",
  "AI・画像生成": "ai-tools",
  "AI・開発ツール": "ai-tools",
  "SaaS Pricing": "saas-pricing",
  "SaaS・生産性": "saas-pricing",
  "クラウド": "saas-pricing",
  "データベース": "saas-pricing",
  "CSS Tools": "css-design",
  "Color Tools": "css-design",
  "Design": "css-design",
  "Design Tools": "css-design",
  "Text & String Tools": "text-tools",
  "Text": "text-tools",
  "Language": "text-tools",
  "Education": "text-tools",
  "学習・教育": "text-tools",
  "Data Format Tools": "data-format",
  "Encoding & Decoding": "encoding",
  "Image Tools": "image-tools",
  "Photography": "image-tools",
  "Print": "image-tools",
  "Finance": "tax-tools",
  "Tax Tools": "tax-tools",
  "Tax": "tax-tools",
  "金融・投資": "tax-tools",
  "暗号資産・Web3": "tax-tools",
  "Japanese Tools": "life-money",
  "Life Tools": "life-money",
  "Lifestyle": "life-money",
  "Home": "life-money",
  "Architecture": "life-money",
  "Real Estate": "life-money",
  "Auto": "life-money",
  "Health & Fitness": "life-money",
  "Medical": "life-money",
  "Outdoor": "life-money",
  "Pets": "life-money",
  "Aquarium": "life-money",
  "Agriculture": "life-money",
  "日常・生活": "life-money",
  "生活・実用": "life-money",
  "健康・医療": "life-money",
  "健康・生活": "life-money",
  "旅行・お金": "life-money",
  "旅行・ビザ": "life-money",
  "旅行・交通": "life-money",
  "旅行・健康": "life-money",
  "冠婚葬祭": "life-money",
  "占い・カレンダー": "life-money",
  "育児・子育て": "life-money",
  "自動車・交通": "life-money",
  "農業・園芸": "life-money",
  "スポーツ": "life-money",
  "スポーツ・フィットネス": "life-money",
  "ペット": "life-money",
  "EC Tools": "ec-shipping",
  "EC": "ec-shipping",
  "Business Tools": "business-tools",
  "Business": "business-tools",
  "Marketing": "business-tools",
  "Productivity": "business-tools",
  "Legal": "business-tools",
  "SNS": "business-tools",
  "SNS・マーケティング": "business-tools",
  "ビジネス・IT": "business-tools",
  "ビジネス・SaaS": "business-tools",
  "ビジネス・行政": "business-tools",
  "仕事・生産性": "business-tools",
  "生産性・仕事術": "business-tools",
  "プロジェクト管理": "business-tools",
  "ツール・便利": "business-tools",
  "メール・通信": "business-tools",
  "Labor Tools": "labor-tools",
  "Labor": "labor-tools",
  "HR": "labor-tools",
  "Creator Tools": "creator-tools",
  "Video": "creator-tools",
  "Music": "creator-tools",
  "Craft": "creator-tools",
  "Music・Entertainment": "creator-tools",
  "音楽": "creator-tools",
  "音楽・エンタメ": "creator-tools",
  "Cooking Tools": "cooking-tools",
  "Cooking": "cooking-tools",
  "料理・食": "cooking-tools",
  "趣味・食": "cooking-tools",
  "Game Tools": "game-tools",
  "Gaming": "game-tools",
  "ゲーム": "game-tools",
  "Developer Tools": "dev-tools",
  "Accessibility": "dev-tools",
  "Web Development": "dev-tools",
  "通信・API": "dev-tools",
  "SEO Tools": "dev-tools",
  "Minifier Tools": "dev-tools",
  "Time & Date": "dev-tools",
  "Math": "math-stats",
  "Math & Science": "math-stats",
  "Statistics": "math-stats",
  "Physics": "math-stats",
  "Engineering": "math-stats",
  "数学・計算": "math-stats",
  "統計・データ分析": "math-stats",
  "DIY": "life-money",
  "カー用品・DIY": "life-money",
  "建築・土木": "life-money",
  "環境・エコ": "life-money",
  "趣味・DIY": "life-money",
};

export function getCategorySlugForToolCategory(category: string): string | undefined {
  return categorySlugByName[category];
}
